### ISSUE TITLE
[QUESTION][Phone number input - invalid country code search returns undefined]

### ISSUE THREAD

**Issue by subitra** [LouisMazel/maz-ui#1010]
## Describe the bug
When an invalid country code is input in the country code search, see that undefined is displayed.
I have seen the sandbox examples, where i see an icon is displayed when invalid country code is searched.
Is there any configuration required for this? 
Sandbox [example](https://codesandbox.io/p/sandbox/mazphonenumberinput-gjfsd?file=%2Fsrc%2FApp.vue)
![image](https://github.com/LouisMazel/maz-ui/assets/41865621/91cb780e-7470-43df-b66a-d958ce17fec3)

## To Reproduce
Enter any invalid country code like 4567 in the country code search bar, see undefined

## Expected behavior
Display information icon/message when invalid country code is searched.

## Screenshots
<img width="398" alt="image" src="https://github.com/LouisMazel/maz-ui/assets/41865621/38fb1e3e-d9db-4702-853b-24addb6afd65">

Note: I have added some customizations to the field css

**Comment by LouisMazel** [comment]
Hi @subitra, 

Thanks for your feedback. Which version of maz-ui do you use?

----

With the last version (v3.37.7), I don't have this behavior, the icon is displayed when the search has no results

![image](https://github.com/LouisMazel/maz-ui/assets/12446546/8f271248-a01a-4bfc-9968-4e52c9326034)

----

You can test it in the documentation: https://maz-ui.com/components/maz-phone-number-input

**Comment by LouisMazel** [comment]
@subitra Do you still have the error with the latest version?

**Comment by subitra** [comment]
I am using Vue version 2 and it is not supporting the latest maz-ui version, is it possible to make it working using maz-ui version 2.4.7
