### ISSUE TITLE
[fetch-country don`t work][<maz-phone-number-input>]

### ISSUE THREAD

**Issue by EugeneVaida** [LouisMazel/maz-ui#102]
**Describe the bug**
fetch-country prop do not work, but few days ago it did, defaultCountryCode is still working but i need to use dynamic fetch country if it possible

**Expected behavior**
after rendering main component phone-input should be initialized with fetched country but it empty

**Screenshots**
![image](https://user-images.githubusercontent.com/36773117/93566073-1e2e1000-f995-11ea-9378-ed1e100a0832.png)
![image](https://user-images.githubusercontent.com/36773117/93566117-330aa380-f995-11ea-9b51-eec49f31e47f.png)

**Desktop (please complete the following information):**
 - OS: [linux ubuntu 20.04 lts]
 - Browser [chrome, firefox]
 - Version [83 version chrome, 80 version firefox]

**Comment by LouisMazel** [comment]
Hi @EugeneVaida,

It will be solved in the next release. Please follow: 

- **[Release PR](https://github.com/LouisMazel/maz-ui/pull/101)**
- **[Bug fix PR](https://github.com/LouisMazel/maz-ui/pull/103)**

Thanks for your feedback 🔥

**Comment by LouisMazel** [comment]
Solved in [v1.4.2](https://github.com/LouisMazel/maz-ui/releases/tag/v1.4.2)
