### ISSUE TITLE
[BUG][MazPicker]

### ISSUE THREAD

**Issue by ihorbond** [LouisMazel/maz-ui#104]
**Describe the bug**
After selecting the date or time for the first time the picker won't open again

**To Reproduce**
Add picker with following options
<MazPicker
            v-model="pickerValue"
            :autoClose="true"
            :double="true"
          />
Open picker, select any date or time. The picker autocloses as expected but when you try to open it again it won't open anymore. I also noticed that when I select hour the minutes portion is automatically set to the current time, not sure if it's by design or a bug though.

**Expected behavior**
User should be able to reopen the picker

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.6 
 - Browser: Chrome 
 - Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
Not really. It's a clean slate Vue project with only this component being rendered on a page

**Comment by LouisMazel** [comment]
Hi @ihorbond,

Thanks for your feedback ! 🔥 

I found the two bugs, I will release soon. 
I keep you in touch

**Comment by LouisMazel** [comment]
Released in **[v1.4.5](https://github.com/LouisMazel/maz-ui/releases/tag/v1.4.5)**

**Comment by ihorbond** [comment]
Thank you !
