### ISSUE TITLE
Whether to consider multi-language support

### ISSUE THREAD

**Issue by Jing-sir** [LouisMazel/maz-ui#1053]
I think it would be a great thing if the UI framework could support multiple languages.

**Comment by LouisMazel** [comment]
Hi @Jing-sir,

Do you any example ? I think all the text in components are editable with slots or props

**Comment by Jing-sir** [comment]
Thank you for your reply, in my mind, every component in the ui framework has built-in behavior, and I think you have this framework, If there is no built-in text, each text can be replaced, I think it is a great experience, I will feel the framework, Thanks for contributing to nuxt 3
