### ISSUE TITLE
[FEATURE] : Getting Number Carier Information

### ISSUE THREAD

**Issue by Ulrich-Mbouna** [LouisMazel/maz-ui#1059]
It's possible to get Carier information of number as showed in this image ?

![image](https://github.com/LouisMazel/maz-ui/assets/60409730/28f09daf-900a-477a-97ff-52e8f55a9476)

Thank you

**Comment by LouisMazel** [comment]
Unfortunately not, libphonumber-js don't have this feature.

In thier documentation:  

> Doesn't provide the equivalent of libphonenumber's formatNumberForMobileDialing() function that formats a number for dialing using a mobile phone within the country: dialing local numbers from a mobile phone is a bit more complicated in some countries like Brazil or Colombia where they require adding ["carrier codes"](https://www.bandwidth.com/glossary/carrier-identification-code-cic/) when making a call. Since libphonenumber-js is not a dialing library (we're not Android phone operaing system), it doesn't prepend any "carrier codes" when formatting phone numbers, though it does parse such "carrier codes" correctly

> Doesn't provide "geolocation" by a phone number.

**Comment by Ulrich-Mbouna** [comment]
Is there any solution in js or ts World to accomplish this thing? 🤔
