### ISSUE TITLE
[BUG][<MazPhoneNumberInput>]

### ISSUE THREAD

**Issue by code-mode** [LouisMazel/maz-ui#106]
**Describe the bug**
The method inside "v-on:input" firing twice after initial loading of template. 

**To Reproduce**

```
<template>
    <div>
        <MazPhoneNumberInput v-model="phone" v-on:input="testInput" />
    </div>
</template>

<script>
import {MazPhoneNumberInput} from 'maz-ui';

export default {
    components: {MazPhoneNumberInput},
    data() {
        return {
            phone: '',
        }
    },
   methods: {
        testInput(){
            console.log('I must fire only on input');
        }
}

```
**Expected behavior**
testInput() with console.log must fire only when user types something inside input field. 

**Screenshots**
![picture](https://user-images.githubusercontent.com/15573248/94553451-38070700-0261-11eb-9e02-f66d69cbc152.jpg)

**Comment by LouisMazel** [comment]
Solved & released in **[v1.4.5](https://github.com/LouisMazel/maz-ui/releases/tag/v1.4.5)**
