### ISSUE TITLE
[Issue][<MazSelect>] The search function does not work with languages other than English and numbers

### ISSUE THREAD

**Issue by IamPaulJ** [LouisMazel/maz-ui#1061]
## Describe the bug

The search function does not work with languages other than English and numbers, such as Chinese, Japanese, and Korean.

## To Reproduce

1. Add <maz-select> component
2. search true.
3. input search keyword with multilingual

## Expected behavior

Search should work normally.

**Comment by LouisMazel** [comment]
Hi @IamPaulJ 

Thanks for your feedback. 
Can you provide an example to help to fix it? 
Could you edit this stackblitz with your code : [https://stackblitz.com/edit/maz-ui-select](https://stackblitz.com/edit/maz-ui-select?file=app.vue,package.json)

**Comment by IamPaulJ** [comment]
Yes, I can.
https://stackblitz.com/edit/maz-ui-select-bakxx6

Thank you for your quick response.


2024년 4월 24일 (수) 오전 2:37, Mazel ***@***.***>님이 작성:

**Comment by IamPaulJ** [comment]
Here is a gif of this issue.
![ezgif-2-e9bd0be506](https://github.com/LouisMazel/maz-ui/assets/137845484/6517c525-9b73-44b5-a286-39a979bc7d65)

**Comment by LouisMazel** [comment]
Thank you a lot ! 

The bug comes from the standardization of strings which is in NFC format, it is not compatible with accented (Chinese, Japanese, etc) or Cyrillic writing.

I keep you in touch when it's fixed 🙂

**Comment by LouisMazel** [comment]
Issue fixed and release in [v3.42.3](https://github.com/LouisMazel/maz-ui/releases/tag/v3.42.3)

Enjoy !

**Comment by LouisMazel** [comment]
I updated the reproduction link (stackblitz) with the new version if you want to test it.

<img width="321" alt="image" src="https://github.com/LouisMazel/maz-ui/assets/12446546/23135121-2f9a-45de-bd89-244b636f46f9">
