### ISSUE TITLE
[Issue][MazInputTags] - Confusion dans la suppresion de string & la supression du tag

### ISSUE THREAD

**Issue by Pierre-Saigot** [LouisMazel/maz-ui#1063]
## Describe the bug

Hello ! Je me permets de te faire un retour en français. Lorsque j'utilise ton composant InputTags, j'ai un bug que l'on peut reproduire également sur ta documentation. Lorsqu'on est en train de créer un tag et qu'on fait un backspace pour changer une lettre ou autre, il y a un bug : cela supprime le tag précédent. Je t'ai fait une capture vidéo pour te montrer, ce sera plus parlant.

Je précise que à aucun moment je bouge ma souris dans le clip.

Merci pour cette lib 🙏🏼

## Screenshots
![Enregistrement-de-l’écran-2024-04-26-à-14 41 00](https://github.com/LouisMazel/maz-ui/assets/10871790/c3c93521-dd30-48b3-bc0e-4012fe137e33)

## Desktop (please complete the following information)

- Browser Chrome - Version 124.0.6367.78
- Version de la lib 3.42.6

**Comment by LouisMazel** [comment]
Hello @Pierre-Saigot, 

Merci pour ton retour ! Y'avait un petit bug sur le check de l'input value.
C'est corrigé dans la v3.42.7, le changelog [ici](https://github.com/LouisMazel/maz-ui/releases/tag/v3.42.7)

Enjoy 🙂
