### ISSUE TITLE
[Issue][PhoneInput] Duplicate element IDs when passing a custom ID

### ISSUE THREAD

**Issue by cmstolper** [LouisMazel/maz-ui#1066]
## Describe the bug

When using the `id` prop of `MazPhoneNumberInput` to pass a custom ID to its input, duplicate element IDs appear between the intended `input` and a parent `div`.

## To Reproduce

1. Set an `id` attribute/prop on the `<MazPhoneNumberInput>` component
2. Observe multiple elements get set with this id

## Expected behavior

Only the intended input element should have the specified element id set.

## Additional context

On version 3.31.6. This may be due to using a native attribute name of `id` that [falls through](https://vuejs.org/guide/components/attrs.html#disabling-attribute-inheritance), causing both the intended element and some parent element to get the custom ID applied. There isn't a duplication problem if the `id` prop isn't set.

**Comment by cmstolper** [comment]
If I get a chance, I'll try to pinpoint the issue and create a PR, but I may not be able to anytime soon.

**Comment by LouisMazel** [comment]
Effectively, I fixed it when I completely rewrote this component. 

I close the issue. 

Thanks for your feedback 🙂
