### ISSUE TITLE
[FEATURE] MazInputCode, support keyArrowLeft, Right and override value

### ISSUE THREAD

**Issue by KumJungMin** [LouisMazel/maz-ui#1067]
## Is your feature request related to a problem? Please describe
- MazInputCode is useful for authentication.
- For example, apple website is provide a similar InputCode.
- Apple website Input is support arrowLeft, right and override value :)
- This movement is useful for user, that hopes edit the value.

https://github.com/LouisMazel/maz-ui/assets/37934668/7e36be94-db94-454e-bde4-786946bb0db5

## Describe the solution you'd like
- I propose to support the arrowLeft, right and override value on default function :)

**Comment by LouisMazel** [comment]
Hi @KumJungMin,

Really a good idea for accessibility!
I'll implement it soon and I'll keep you posted on the progress here!

Thanks for your feedback

**Comment by LouisMazel** [comment]
Feature included in [v3.43.3](https://github.com/LouisMazel/maz-ui/releases/tag/v3.43.3) 

Enjoy 🎉
