### ISSUE TITLE
[The Placeholder field is responsible for Label, but placeholder of input is expected][<MazPhoneNumberInput>]

### ISSUE THREAD

**Issue by Veronika-dev** [LouisMazel/maz-ui#1076]
Hi, I use `MazPhoneNumberInput` and I need a placeholder of input. However, floating label is shown instead of placeholder.

## To Reproduce

1. Fill a `placeholder` property of MazPhoneNumberInput.
```
<MazPhoneNumberInput
    placeholder="Placeholder text"
    ...
/>
```
2. Or you can use 
```
<MazPhoneNumberInput
    :translations="{
       phoneInput: {
           placeholder: "Placeholder text"
       }
    }"
    ...
/>
```
3. You will get a floating label (see the screenshot)

## Screenshots

<img width="381" alt="Снимок экрана 2024-05-07 в 14 38 43" src="https://github.com/LouisMazel/maz-ui/assets/24383434/b770db8a-4ac6-43fd-8dd2-813139c9d68f">

## Expected behavior

I expected placeholder of the input. But I got a floating label.

## Desktop

- OS: MacOS 14.4.1
- Browser Chrome 
- Version 124.0.6367.119

**Comment by LouisMazel** [comment]
Hi @Veronika-dev,

Thanks for your feedback. 

It's solced in [v3.43.4](https://github.com/LouisMazel/maz-ui/releases/tag/v3.43.4)

Enjoy
