### ISSUE TITLE
[Issue][<PhoneInput>] Clearing v-model doesn't clear input

### ISSUE THREAD

**Issue by patsok** [LouisMazel/maz-ui#1086]
## Describe the bug

Clearing v-model doesn't clear input - it only updates when v-model is valid number, so when I'm clearing v-model with undefined or empty string or null its value inside isn't cleared.

## To Reproduce

1. Set v-model to valid number
2. Set v-model to undefined/null/empty string

## Expected behavior

Input with country and phone number should be empty as on initial state.

## Screenshots

in Vue Dev Tools you can see modelValue null on MazPhoneNumberInput
![obraz](https://github.com/LouisMazel/maz-ui/assets/23488255/b023398a-3bf1-4a85-a7e8-c777e0a7aafd)
on PhoneInput component it has value before clearing
![obraz](https://github.com/LouisMazel/maz-ui/assets/23488255/68363688-6898-4d87-8cdf-e7b5eee0c73c)

## Desktop (please complete the following information)

- OS: Linux/Ubuntu
- Browser Chrome
- Version 123.0.6312.122

**Comment by LouisMazel** [comment]
Solved in [v3.44.0](https://github.com/LouisMazel/maz-ui/releases/tag/v3.44.0)
