### ISSUE TITLE
[Issue][< MazRadioButtons >]

### ISSUE THREAD

**Issue by davidramosweb** [LouisMazel/maz-ui#1087]
## Describe the bug

When you have multiple MazRadioButtons components on the same page, and they have the same 'values,' the second component stops working correctly because the 'for' attributes of the label for both components coincide, since these are generated with the index and the value.

## To Reproduce

1. Add two MazRadioButtons components.
2. Ensure that the values of options match in both components.
3. Click on one of the options in the second component.
4. Instead of changing the selection in the second component, it changes in the first one.

## Expected behavior

When multiple MazRadioButtons components are present on the same page and their options have identical values, each component should independently manage its selected option. Clicking on an option within one component should only affect the selection within that specific component, maintaining the integrity and functionality of all MazRadioButtons components on the page

## Screenshots

![image](https://github.com/LouisMazel/maz-ui/assets/4605169/6044ac80-69c0-43dc-8f75-662fc32b77e9)

## Desktop (please complete the following information)

- OS: MacOs
- Browser [chrome, safari]
- Version [124.0.6367.201, 17.4.1]

## Additional context

[Here is a sandbox with an example](https://codesandbox.io/p/devbox/mazradiobuttons-fy62dt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwufx24y00073b6isoscgrs3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwufx24y00023b6itmb4dpbu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwufx24y00043b6iqrspwc7d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwufx24y00063b6int63yfbp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwufx24y00023b6itmb4dpbu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwufx24x00013b6irjga8sgr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwufx24y00023b6itmb4dpbu%2522%252C%2522activeTabId%2522%253A%2522clwufx24x00013b6irjga8sgr%2522%257D%252C%2522clwufx24y00063b6int63yfbp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwufx24y00053b6iloe1gl39%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwufx24y00063b6int63yfbp%2522%252C%2522activeTabId%2522%253A%2522clwufx24y00053b6iloe1gl39%2522%257D%252C%2522clwufx24y00043b6iqrspwc7d%2522%253A%257B%2522id%2522%253A%2522clwufx24y00043b6iqrspwc7d%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwufx24y00033b6ingnkp9o1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwufx24y00033b6ingnkp9o1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by LouisMazel** [comment]
Solved in [v3.44.0](https://github.com/LouisMazel/maz-ui/releases/tag/v3.44.0)
