### ISSUE TITLE
[FEATURE] Add blur event on InputTags for add other tags

### ISSUE THREAD

**Issue by damevin** [LouisMazel/maz-ui#1090]
## Is your feature request related to a problem? Please describe

I think the component InputTags should be improved for better UX, i use InputTags in my own application and users are frustrated because they have to press enter for add another tag, in some cases in my usage, they only need to add one tag in this form.

## Describe the solution you'd like

Adding a new prop  maybe, `addTagOnBlur` and if it's set at true, we call the function `addTags` on blur ?

Maybe you have a better solution 😇

## Describe alternatives you've considered

_I've tried to tinker the code for add the event directly on the component `<InputTags/>`, but we loose reactivity_

## Additional context

_Exemple of actual usage :_ 

A user paste the value, and submit directly, the tag is not 
![Screenshot-YlvAPD39091031](https://github.com/LouisMazel/maz-ui/assets/72107589/97505f73-9887-4ee2-8e5d-02f91c31f777)

---

_Exemple of expected usage with the prop `addTagOnBlur`:_

A user paste the value, when the blur event is detected, create a new tag
![Screenshot-oDnxZiF7091347](https://github.com/LouisMazel/maz-ui/assets/72107589/b34ff4c6-603c-410b-b7b9-9aa49bddcb80)

I can help on that point and create an MR, but first i'd like to know your opinion @LouisMazel 
Thanks for all 🙏

**Comment by LouisMazel** [comment]
Solved in [v3.44.0](https://github.com/LouisMazel/maz-ui/releases/tag/v3.44.0)
