### ISSUE TITLE
[Issue][<Use Components in custom library with vue 3 TS and Vite>]

### ISSUE THREAD

**Issue by denisibanez** [LouisMazel/maz-ui#1097]
## Describe the bug

I have a library built with Vue 3 and Vite, using TS, I use Quasar and other third-party libraries without problems.

However, when using your library, with the MazPhoneNumberInput component imported in a wrapper component, when I build my library I receive the error below.

## Screenshots
![Captura de Tela 2024-06-18 às 17 22 40](https://github.com/LouisMazel/maz-ui/assets/13679915/c7579bb5-3f43-4044-be27-c2907e951cbc)

**Comment by denisibanez** [comment]
If I try to import this component globally, it just doesn't find it

**Comment by LouisMazel** [comment]
Hi @denisibanez,

Can you share the code where you implement the component or a reproduction link with stackblitz ? 

You can use this base: https://stackblitz.com/edit/maz-ui-vue3-phonenumber
