### ISSUE TITLE
[Bug][phone-number-input] on edit behaviour

### ISSUE THREAD

**Issue by vasilyevd** [LouisMazel/maz-ui#1104]
## To Reproduce

1. Go to demo https://maz-ui.com/components/maz-phone-number-input.html
2. Try change (delete phone chars in some cases)
3. See behaviour on video

https://github.com/LouisMazel/maz-ui/assets/2834603/980d76d5-d1d0-4ad0-8c2e-fa683cf7fc8b

**Comment by LouisMazel** [comment]
A fix is release in the [v3.47.0](https://github.com/LouisMazel/maz-ui/releases/tag/v3.47.0)

You can disable the auto-format: https://maz-ui.com/components/maz-phone-number-input#auto-formatting

Enjoy
