### ISSUE TITLE
[Issue] npm package is misconfigured

### ISSUE THREAD

**Issue by jacobg** [LouisMazel/maz-ui#1108]
The source code contains peer dependency for unplugin-vue-components at version 0.27.0:
https://github.com/LouisMazel/maz-ui/blob/0ee50bd5b4f4e55b26e638df11919e0fe968d7c2/packages/lib/package.json#L107

However, on npm it's 0.26.0:
https://www.npmjs.com/package/maz-ui?activeTab=code

Since there was an npm release more recently than the update to package.json, it would be expected to match.

**Comment by LouisMazel** [comment]
HI @jacobg,

Thanks for your feedback, this is will be fixed in the next version

**Comment by LouisMazel** [comment]
[v3.45.0](https://github.com/LouisMazel/maz-ui/releases/tag/v3.45.0) is released and fix this issue
