### ISSUE TITLE
[BUG][<MazPhoneNumberInput>]

### ISSUE THREAD

**Issue by ThibaultWalterspieler** [LouisMazel/maz-ui#111]
**Describe the bug**

The input doesn't load the style of the component (here the **MazInput**). Check the screenshot 

**To Reproduce**

1. Install Maz-UI : `npm i maz-ui -S`
2. Import **MazInput** in Vue file like that : 
```vue
<template>
  <Layout>
    <MazInput
      v-model="contactFormData.fullname"
      placeholder="Nom complet"
      autocomplete="new-name"
      class="maz-mb-3"
      left-icon-name="person"
      right-icon-name="favorite"
      clearable
    />
    <MazPhoneNumberInput v-model="contactFormData.phone" />
  </Layout>
</template>


<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { MazPhoneNumberInput, MazInput } from 'maz-ui';

@Component({
  components: { MazInput, MazPhoneNumberInput },
  filters: {},
})
export default class Contact extends Vue {
  contactFormData = {
    email: '',
    fullname: '',
    phone: '',
    content: '',
  };
}
</script>
```
3. Compile

**Expected behavior**
Display the inputs with Maz default style

**Screenshots**
The input display : 

<img width="312" alt="Screenshot 2020-11-01 at 20 58 05" src="https://user-images.githubusercontent.com/15186627/97812938-26ac8280-1c85-11eb-90db-b1751dcfe9ab.png">

**Desktop:**
 - OS : macOS Catalina v10.15.6
 - Browser : Google Chrome  v86.0.4240.111
 - Maz-UI : v1.4.19
 - Node : v12.18.3

**Additional context**

This sample of code is running on Gridsome (v0.7.0) in TypeScript (4.0.3). The style of the component isn't overwrite.

**Comment by LouisMazel** [comment]
Hi @ThibaultWalterspieler, 

You have to import the needed CSS files. Two way to do this : 

## Manually imports

```js
import { MazPhoneNumberInput, MazInput } from 'maz-ui'

// SCSS
import 'maz-ui/lib/scss/base.scss'
import 'maz-ui/lib/scss/maz-input.scss'
import 'maz-ui/lib/scss/maz-phone-number-input.scss'

// or, CSS
import 'maz-ui/lib/css/base.scss'
import 'maz-ui/lib/css/maz-input.scss'
import 'maz-ui/lib/css/maz-phone-number-input.scss'
```

## Auto CSS import with babel

**On demand doc in get started : https://louismazel.github.io/maz-ui/documentation/get-started/**

```bash
npm install babel-plugin-component -D
```
```js
// .babelrc
{
  plugins: [
    [
      'component', {
        libraryName: 'maz-ui',
        styleLibraryName: 'css' // or scss
      }
    ]
  ]
}
```

Then, the CSS files will be imported automatically

```js
import { MazBtn, MazInput } from 'maz-ui'
```

**Comment by RonnieMamangunQx** [comment]
Hi @LouisMazel,

Just wanted to ask why the input field is accepting characters? Is there any option or props that I need to set to make it accept the numbers only?
![image](https://user-images.githubusercontent.com/76149105/184107404-83a450b3-33ca-4acf-89e6-07815a0297d1.png)

Thanks in advance.
