### ISSUE TITLE
[Issue][MazSelect] Wrong color of selected item in primary variant

### ISSUE THREAD

**Issue by ncls-alien** [LouisMazel/maz-ui#1116]
## Describe the bug

The color of the selected element is not the main shade of primary when color is set to "primary" or left undefined.

## To Reproduce

1. Use the MazSelect component in your app and set color to "primary" or leave undefined

## Expected behavior

The color should be the primary color chosen in the theme.
Also the default slot should cover the whole option element and not just it's contents.

## Screenshots

![grafik](https://github.com/user-attachments/assets/d92b285b-81f0-4811-9aef-feb5b01609ef)
![grafik](https://github.com/user-attachments/assets/e9528db7-d8d1-4a54-807e-9733f091f95e)

## Desktop (please complete the following information)

- OS: Windows 11
- Browser Chrome
- Version 126.0.6478.182

**Comment by LouisMazel** [comment]
Hi @ncls-alien, 

This component uses a variant of the selected color (primary by default). It's a UI choice. 
I think you must adjust your `var(--maz-color-primary-200)` to have a better UI.
