### ISSUE TITLE
[BUG] MazPhoneNumberInput displaying E164 format in form instead of formatted national number, since version 1.4.0

### ISSUE THREAD

**Issue by jacobg** [LouisMazel/maz-ui#112]
**Describe the bug**
MazPhoneNumberInput displaying E164 format in national number input box instead of formatted national number, since version 1.4.0 and through current version 1.4.19. It displays find 1.3.1.

**To Reproduce**
Render MazPhoneNumberInput with v-model bound to "+12125553333".

**Expected behavior**
Form input box displays US for country code, and (212) 555-3333 in national number input box.

**Screenshots**
version 1.4.0+
<img width="549" alt="Screen Shot 2020-12-07 at 9 20 45 AM" src="https://user-images.githubusercontent.com/736985/101362348-00729780-386e-11eb-952e-32b108ec5000.png">
version 1.3.1
<img width="554" alt="Screen Shot 2020-12-07 at 9 20 59 AM" src="https://user-images.githubusercontent.com/736985/101362372-08323c00-386e-11eb-913a-b0483969c790.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 86

**Smartphone (please complete the following information):**

**Additional context**
Here is the code sandbox repro:
https://codesandbox.io/s/mazphonenumberinput-bind-bug-u88gy?file=/src/App.vue

**Comment by jacobg** [comment]
Here is a working repro example:
https://codesandbox.io/s/mazphonenumberinput-bind-bug-u88gy?file=/src/App.vue

If you change the maz-ui dependency version to 1.3.1, you'll see the phone number renders correctly.

Here is the screenshot of 1.4.1 and later:
<img width="549" alt="Screen Shot 2020-12-07 at 9 20 45 AM" src="https://user-images.githubusercontent.com/736985/101362220-d0c38f80-386d-11eb-9692-941f4508b89b.png">

Here is the screenshot of 1.3.1, the last version where it renders correctly:
<img width="554" alt="Screen Shot 2020-12-07 at 9 20 59 AM" src="https://user-images.githubusercontent.com/736985/101362243-dcaf5180-386d-11eb-9eed-83ecab30f19f.png">

I'll update the original comments above with this information.

**Comment by LouisMazel** [comment]
Hi @jacobg ,

Yes I know it... I have done this for better compatibility with all different countries.

I want to have the second format too (`(212) 555-333`), but use this format cause many bugs with the `AsYouType` (number formatting) by [libphonenumber-js](https://www.npmjs.com/package/libphonenumber-js)

Se my answer here: https://github.com/LouisMazel/maz-ui/issues/105#issuecomment-700855382

If you have any solution, I'll take it

**Comment by jacobg** [comment]
It seemed to work fine on version Maz 1.3.1. Are you saying that Russian numbers weren't working then? Do you have an example of a phone number on that version which didn't work? What if you have a prop to allow developer to choose whether to format or not?

**Comment by LouisMazel** [comment]
The issue why have to do this: https://github.com/LouisMazel/maz-ui/issues/90

Try to delete the phone number with backspace: [CodeSandbox - Demo](https://codesandbox.io/s/mazphonenumberinput-ru-q9ib6?file=/src/App.vue)

It's impossible because the `AsYouType` function of `libphonenumber-js` add an `8` at the start of phone number and reformat

**Comment by jacobg** [comment]
Thanks for the example @LouisMazel . Is this only a problem for Russia? If so, I would prefer the better formatted experience for all other countries with just a Russian issue, then a degraded experience for everyone. Is it possible to have a prop to control whether to format? Or maybe just disable formatting specifically for Russia? Are you aware of a `libphonenumber-js` github issue specifically for the russia problem?

**Comment by idesignzone** [comment]
@jacobg solution don't seem to work with latest:
    "libphonenumber-js": "^1.10.47",
    "maz-ui": "^3.17.0",
