### ISSUE TITLE
[Issue with the format date displayed on the input field][<MazPicker>]

### ISSUE THREAD

**Issue by hadelnasr** [LouisMazel/maz-ui#1122]
## Describe the bug

I'm using the MazPicker as shown below

`<MazPicker
                    v-model="registrationForm.identity_expire_date"
                    label=''
                    :state="v$.identity_expire_date.$errors.length ? false : null"
                    id="identity_expire_date"
                    :min-date="today"
                    :max-date="tenYearsFromToday"
                    :locale="locale"
                    :no-header="true"
                    :auto-close="true"
                    class="col-12"
                    :inputDateStyle="{dateStyle: 'medium'}"
                    :placeholder="$t('register.PERSONAL_INFO_SECTION.IDENTITY_EXPIRE_DATE_PLACEHOLDER')"
                />`

The locale will be either **ar** for arabic OR **en** for english

in arabic locale the date is displayed after selecting on the input field as expected: "2024/08/06"
But while in english locale, the date is displayed as Aug 6, 2024

i need to unify both displayed input values to match "YYYY/MM/DD"
i tried the format attribute but in vain, seems that it formats the model value only not the displayed one

## Expected behavior

To display the "YYYY/MM/DD" format on the input field

i'm using maz ui versin 3.44.3

**Comment by hadelnasr** [comment]
@LouisMazel any info regarding this bug?

**Comment by LouisMazel** [comment]
Yes, the format prop option only formats the output template. It is the format of your database, API, etc.

To format the date displayed in the input field, you need to use the `input-date-style` prop option.

These are the options provided to the Intl.DateTimeFormat formatter (it will format the template with the locale).

So in your case, you should use it:

```vue
<template>
  <MazPicker 
   :input-date-style="{ dateStyle: 'short' }" // format: "MM/DD/YY" with locale en
  />
  <!-- or -->
  <MazPicker 
    :input-date-style="{ year: 'numeric', month: '2-digit', day: '2-digit' }"  // format: MM/DD/YYYY with locale en
  />
</template>
```

(The formats `MM/DD/YY` or `MM/DD/YYYY` are the standard format)

But if you want to display the date in `YYYY/MM/DD`, in the next version, I will add a new property option named `input-date-transformer`. This property will be a function with this type of definition:

```typescript
type Transformer = (payload: { formattedDate?: string, value?: PickerValue, locale?: string }) => string
```
> The value arg is the current model value. 

With this data, you can format the displayed date as you want. You have to return the formatted date as you want in string type.

Use like this:

```vue
<template>
  <MazPicker
    v-model="newDateValue"
    id="date-picker"
    label="Select date"
    locale="en"
    :input-date-style="{ year: 'numeric', month: '2-digit', day: '2-digit' }"
    :input-date-transformer="({ formattedDate }) => {
      return formattedDate?.split('/')
        .reverse()
        .join('/');
    }"
  />
</template>
```

**Comment by LouisMazel** [comment]
I just released a new beta version, can you test it and let me know if it's good for you ?

```bash
npm add maz-ui@3.44.4-beta.13
```

I fixed the 2 other issues too : 
- #1120 
- #1121

**Comment by LouisMazel** [comment]
[v3.45.0](https://github.com/LouisMazel/maz-ui/releases/tag/v3.45.0) is released ! Enjoy

**Comment by hadelnasr** [comment]
@LouisMazel i can't express my happiness with your fast response

the 3 issues are resolved, a very big thanks
