### ISSUE TITLE
[BUG][<Phone Input>  Country list closes when clicking scroll bar]

### ISSUE THREAD

**Issue by otsab19** [LouisMazel/maz-ui#113]
**Describe the bug**
Country list closes when clicking scroll bar

**To Reproduce**
When the scroller on the country list is clicked, the close event is emitted.

**Comment by LouisMazel** [comment]
Hi,

Wich browser and system you use ?

Thanks for your feedback

**Comment by otsab19** [comment]
Browsers: Chrome and Firefox. system: Linux and Windows

**Comment by LouisMazel** [comment]
Is the bug present here? -> https://codesandbox.io/s/mazphonenumberinput-gjfsd

**Comment by nyunyu95** [comment]
> Is the bug present here? -> https://codesandbox.io/s/mazphonenumberinput-gjfsd

But is not present on the sandbox but I'm getting the same issue only when the input is used inside a vuetify dialog.
Outside of this component, the input is working as expected (i just moved from your old library to this one for this exact same problem).

Hope you can help !

Regards,

**Comment by otsab19** [comment]
It works on the sandbox. I created a new project with Maz and it works. 
But its not working on separate project, it is using vue bootstrap.

**Comment by otsab19** [comment]
Apparently it doesn't work if I put the phone input component inside of the bootstrap form group.
