### ISSUE TITLE
[vue3][maz-ui] maz-ui couldnt use in vue3

### ISSUE THREAD

**Issue by JinhaoZhao** [LouisMazel/maz-ui#1130]
![1](https://github.com/user-attachments/assets/d8eeb349-08a3-4ac9-8e89-ee579f49d70a)
![2](https://github.com/user-attachments/assets/0a3127ba-6373-407d-b5ab-294b2f6f6d3b)
My project is use vue3, and I want to import the maz-ui in my project, but i got some promblems while import. Does there have some ways to fix the above problems

**Comment by LouisMazel** [comment]
Hi @JinhaoZhao,

Your errors are strange. `mergeModels` and `useModel` are not exported helpers of Vue 3. 
Which version of Vue have you installed?

Maybe it's a Webpack bug, please refer to this [issue](https://arc.net/l/quote/yisvljox)
