### ISSUE TITLE
[Issue][MazTabs] autoScroll doesn't work with initial model value

### ISSUE THREAD

**Issue by thinknirmal** [LouisMazel/maz-ui#1135]
## Describe the bug

When using `MazTabs` with `v-model` and if the model value is pre-populated with a certain tab number, autoScroll does not scroll the `MazTabsBar` to the relevant position.

## To Reproduce

```html
<script setup lang="ts">
  const activeTab = ref(7);
  const tabs: MazTabsBarItem[] = [
    { label: 'Tab Number 1' },
    { label: 'Tab Number 2' },
    { label: 'Tab Number 3' },
    { label: 'Tab Number 4' },
    { label: 'Tab Number 5' },
    { label: 'Tab Number 6' },
    { label: 'Tab Number 7' },
  ]
</script>

<template>
  <MazTabs v-model="activeTab">
    <MazTabsBar :items="tabs" no-elevation auto-scroll block/>
  </MazTabs>
</template>
```

## Expected behavior

The `MazTabsBar` should scroll to `Tab Number 7`.

## Desktop

- OS: MacOS Sonoma 14.6.1
- Browser: Chrome
- Version: 127.0.6533.120 (Official Build) (arm64)

**Comment by LouisMazel** [comment]
Hi @thinknirmal, 

Fixed into [v3.45.3](https://github.com/LouisMazel/maz-ui/releases/tag/v3.45.3)

F.Y.I: The auto-scroll feature is enabled by default

Thanks :)
