### ISSUE TITLE
[Issue with the phone number input component][<MazPhoneNumberInput>]

### ISSUE THREAD

**Issue by hadelnasr** [LouisMazel/maz-ui#1139]
## Describe the bug

While selecting some countries and start inputting the phone number, the package added some extra numbers from itself as shown with the below screenshots

## To Reproduce

choose united arab emirates (code +971) 
start typing phone number without leading zero, at success the package appends 0 by itself although the country phone number doesn't restrict adding a leading zero

another case:
choose Anguilla (code +1) 
start typing the phone number by adding 264 then any digits, you'll find the package by itself adding 264 again by itself

## Expected behavior

In the above both cases, the package should obey the values i'm entering

## Screenshots

![1](https://github.com/user-attachments/assets/59c3359a-636e-44db-99fa-c51c01095350)
![2](https://github.com/user-attachments/assets/b1288373-e5a9-481a-a610-140202fdf5ec)

## Desktop 

- OS: [e.g. Linux / Windows]
- Browser [e.g. chromei]

**Comment by hadelnasr** [comment]
@LouisMazel @developerdino @pboos @dnyer11

**Comment by hadelnasr** [comment]
Any info guys plz??

**Comment by hadelnasr** [comment]
@LouisMazel any updates so far?

**Comment by LouisMazel** [comment]
Hi @hadelnasr,

I just came back from vacation, I will take time to fix it soon. May be add an option to disable all auto-format of the phone number.

**Comment by hadelnasr** [comment]
Thanks @LouisMazel for your continuous support
Awaiting your feedback

**Comment by hadelnasr** [comment]
@LouisMazel any updates so far?

**Comment by hadelnasr** [comment]
@LouisMazel any updates please?

**Comment by hadelnasr** [comment]
@LouisMazel please give me expected date for fixing this issue?
thanks for your continuous support

**Comment by hadelnasr** [comment]
@LouisMazel @pboos @developerdino @dnyer11 

any updates guys? please try giving me any estimate??

**Comment by LouisMazel** [comment]
Hi @hadelnasr,

Yes, it's resolved but it's available only in beta for the moment. 
You can use the v3.46.1-beta.4. 

You just have to disable the auto-formatting like this:

```html
<MazPhoneNumberInput
    v-model="phoneNumber"
    :auto-format="false"
  />
```

Enjoy.

FYI: I will close this issue when the fix is released in v3.46.1

**Comment by hadelnasr** [comment]
@LouisMazel many thanks for your continuous support

**Comment by LouisMazel** [comment]
It's release in the [v3.47.0](https://github.com/LouisMazel/maz-ui/releases/tag/v3.47.0) finally 

Enjoy
