### ISSUE TITLE
MazDropzone - files object name form manipulation.

### ISSUE THREAD

**Issue by EDMONDGIHOZO** [LouisMazel/maz-ui#1147]
## Mazdropzone is great, but i faced some limitation.
when uploading, my backend endpoint requires an object to be like ` {files: {files data}},` but when using  mazdropzone it sends `{files data}`.

i'd like to to know if there is a away i can specify the object name. my backend is on strapi which may be used by other many devs, i can make a middleware which will make the form object as it should be.
but it can be great if its done while in frontend.

cheers.

**Comment by LouisMazel** [comment]
Hi @EDMONDGIHOZO,

You can add the `uploadMultiple: true` option and you can also manipulate the payload by using the formData sending by the `sending` or `sendingmultiple` events: 

# Sending file 

```vue
<template>
  <MazDropzone
    ref="mazDropzoneInstance"
    :options="{ 
      url: 'https://httpbin.org/post',
      headers: { 'My-Awesome-Header': 'header value' },
      acceptedFiles: 'image/jpeg,image/jpg,image/png',
    }"
    @sending="onSending"
  />
</template>

<script lang="ts" setup>
  function onSending(file, xhr, formData) {
    formData?.append('files', file)
  }
</script>
```

# Sending multiples Files

```vue
<template>
  <MazDropzone
    ref="mazDropzoneInstance"
    :options="{ 
      url: 'https://httpbin.org/post',
      headers: { 'My-Awesome-Header': 'header value' },
      acceptedFiles: 'image/jpeg,image/jpg,image/png',
      uploadMultiple: true,
      parallelUploads: 10 
    }"
    @sendingmultiple="onSendingMultiple"
  />
</template>

<script lang="ts" setup>
  function onSendingMultiple(files, xhr, formData) {
    formData?.append('files', files)
  }
</script>
```
