### ISSUE TITLE
Auto-fill/Auto Complete

### ISSUE THREAD

**Issue by MuaviyaImran** [LouisMazel/maz-ui#1156]
## Describe the bug
I am facing issue with auto suggest/auto-fill, as i fill the input by auto-fill suggested by browser, it places the number in country code input and the number input remains empty.

## Expected behavior

by autofill it must fill the country code and and number input seperately

## Screenshots
![Screenshot from 2024-09-19 15-43-40](https://github.com/user-attachments/assets/0a125a89-557a-4c7a-9f9c-7cfe152a3bb4)

## Desktop (please complete the following information)

- OS: [Linux Ubuntu, MAC ]
- Browser [chrome]

**Comment by LouisMazel** [comment]
Hi @MuaviyaImran, 

You can now control the attributes of each field input in `MazPhoneNumberInput` component with `countrySelectAttributes` and `phoneInputAttributes`

By default: 
- countrySelectAttributes = `{ name: 'country', autocomplete: 'off' }`
- phoneInputAttributes = `{ name: 'phone', autocomplete: 'tel', inputmode: 'tel' }`

Adjust these values to have good behavior. 

F.I: You can add any attributes on each field input.

Release: https://github.com/LouisMazel/maz-ui/releases/tag/v3.46.0

**Comment by MuaviyaImran** [comment]
@LouisMazel  I really appreciate your response. I've tested the modifications, they seem to be functioning, my problem has been fixed, and if you'd like, I may contribute to your library's open source project.
Again, Thank you..!
