### ISSUE TITLE
[FEATURE] Use exact-match search in MazSelect inside MazPhoneNumberInput

### ISSUE THREAD

**Issue by thinknirmal** [LouisMazel/maz-ui#1157]
## Is your feature request related to a problem? Please describe

The country search in `MazPhoneNumberInput` is not straightforward since the `MazSelect` inside it uses Levenshtein Distance to calculate matches. In many cases, this doesn't bring the intended country to the top of the list. Try typing "malaysia" or "india" and see the results that come up in the first few keystrokes.

## Describe the solution you'd like

`MazSelect` could take a prop to specify the matching score threshold, so that the `MazPhoneNumberInput` usage could set this to `1` (I am speaking after taking a quick look at the code so I might be totally wrong with the approach here).

## Additional context

<img width="365" alt="image" src="https://github.com/user-attachments/assets/9f3dacc4-8c0d-4d67-aa7b-c41052b13614">
<img width="365" alt="image" src="https://github.com/user-attachments/assets/d80e1cb0-3858-439b-ace9-c2a9f6b2b575">

**Comment by thinknirmal** [comment]
I probably spoke too soon because I just now saw this commit: https://github.com/LouisMazel/maz-ui/commit/018dce7e7c39c8fd83242cd2e272f7c5970fcecd

I believe it would still be a good idea to have a control on the distance threshold.

**Comment by LouisMazel** [comment]
Hi @thinknirmal,

Good idea!
I just released a new version ([v3.45.5](https://github.com/LouisMazel/maz-ui/releases/tag/v3.45.5)) with a new prop option for MazSelect : `search-threshold`

To have the exact-match, you can set this prop to 1

```html
<MazSelect :search-threshold="1" />
```

Thanks for your feedback!

**Comment by thinknirmal** [comment]
Thank you, @LouisMazel. Does this also add a prop to the `MazPhoneNumberInput`? Otherwise one is forced to extend and override that component to use this functionality within the country selector.
