### ISSUE TITLE
[Issue][<MazPhoneNumberInput]

### ISSUE THREAD

**Issue by wug-ge** [LouisMazel/maz-ui#1178]
## Describe the bug

I'm receiving the following error in my console log: 
`DOMException: Document.querySelector: '#country-selector-flag-button-MazPhoneNumberInput-v:0-0' is not a valid selector`

The Component seems to work fine though. (I think, did not test everything yet.)
The phone number only gets displayed once I press into the input box though at first load. (the html input element has an empty string value, but the vue component "MazInput" seems to have the correct value)

## To Reproduce

- Install maz-ui with Nuxt
- use phone number component
- make a click anywhere on the page

My Component:
`
  <MazPhoneNumberInput
    name="phone-number"
    v-model="user.telephone"
    required
    class="w-full"
    :preferred-countries="['AT', 'DE', 'CH']"
    default-country-code="AT"
    :translations="{
      countrySelector: {
        placeholder: $t('chooseCountry'),
        error: $t('chooseCountry'),
        searchPlaceholder: $t('searchCountry'),
      },
      phoneInput: {
        placeholder: $t('phoneNumber'),
        example: $t('example') + ':',
      }
    }"
    :country-locale="$i18n.locale"
    no-example
  />`

## Expected behavior

Show value of phone number directly when you load the page, not after click. Don't throw unnecessary error.

## Desktop (please complete the following information)

- OS: Linux
- Browser Firefox
- Version 132

**Comment by wug-ge** [comment]
I managed to find a Workaround to display the phone number directly. It is an ugly solution and I don't understand why it is needed, but maybe it helps with finding the issue:

`onMounted(() => {
  setTimeout(() => {
    const oldNumber  = user.value.telephone 
    user.value.telephone = ''
    setTimeout(() => {
      user.value.telephone = oldNumber
    }, 0)
  }, 0)
})
`

With this code the phone number shows correctly at page load. (not sure if the error I'm getting is related or not to this)

**Comment by LouisMazel** [comment]
Hi @wug-ge,

I released a beta version with the fixes, can you try it and tell me if it's good?

The beta version is: `3.47.2-beta.14`

Install it: 

```
npm install maz-ui@3.47.2-beta.14
```
 
Thanks for your feedback :)

**Comment by wug-ge** [comment]
Hey @LouisMazel !

Thank you for the quick response & fix!
I installed the beta version and can confirm the issue has been resolved, no more error and my phone number gets displayed correctly, everything looks good to me! :)

**Comment by LouisMazel** [comment]
Released in [v3.48.0](https://github.com/LouisMazel/maz-ui/releases/tag/v3.48.0)
