### ISSUE TITLE
No obvious option to include CSS for a component 

### ISSUE THREAD

**Issue by sergeyfilimonov** [LouisMazel/maz-ui#120]
I'd like to use only this component https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input but I could not find a way to import CSS only for this component, I don't want to include all the theme CSS into my project. Is this possible? Thanks!

**Comment by LouisMazel** [comment]
Hi @sergeyfilimonov,

You have 2 choices to do that :

1 - You can use the "on demand" method with `babel-plugin-component` described on the documentation **[Get Started](https://louismazel.github.io/maz-ui/documentation/get-started/)**

2 - Follow this **[example](https://codesandbox.io/s/mazphonenumberinput-gjfsd?file=/src/App.vue)** (in App.vue). You manually import each files

Enjoy
