### ISSUE TITLE
[BUG] MazPhoneNumberInput does not support EN locale

### ISSUE THREAD

**Issue by OlegFomishyn** [LouisMazel/maz-ui#121]
**Describe the bug**
If user set "English" language in Chrome, it will have "en" in the "window.navigator.language" property.
Phone component will show error: "MazPhoneNumberInput: The locale EN is not available" in dev mode. In production mode it will not have default country set.

**To Reproduce**
1. Open Chrome settings
2. Go to "Advanced" settings, then "Languages"
3. Set Language to "English"
4. Open demo page (https://codesandbox.io/s/mazphonenumberinput-check-iran-wtndi?file=/src/App.vue)

**Expected behavior**
Phone component should at least fallback to "en-us" locale or detect country in some other way.

**Screenshots**
![20201201_142446_Ima6GmzN](https://user-images.githubusercontent.com/75313620/100740199-fcafc280-33e0-11eb-8dfb-7a78540fc536.png)
![20201201_142202_pIAsxbrm](https://user-images.githubusercontent.com/75313620/100740211-00dbe000-33e1-11eb-8170-f9f9a2d4b978.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.66

**Comment by LouisMazel** [comment]
Hi @OlegFomishyn,

It's a case bug. I will release a fixe. I keep you in touch.

Thanks for your feedback

**Comment by LouisMazel** [comment]
@OlegFomishyn,

It's normal, because `EN` is not a country, it's a language. 
In your browser settings, you have to choose English (UK) or English (US)

But to fix this, in the next release, if the component get the `EN` locale, I fallback to the `US` locale (more users than `GB`)

**Comment by LouisMazel** [comment]
It's solved in the **[release](https://github.com/LouisMazel/maz-ui/releases/tag/v1.5.14)**
