### ISSUE TITLE
[BUG] Phone number input does not render properly inside framework7-vue

### ISSUE THREAD

**Issue by jacobg** [LouisMazel/maz-ui#126]
**Describe the bug**
The phone number input does not render properly inside framework7-vue. It seems like a styling issue. See screenshot below.

**To Reproduce**
See code sandbox: [https://codesandbox.io/s/f7-maz-vue-dpnej?file=/src/pages/Maz.vue](https://codesandbox.io/s/f7-maz-vue-dpnej?file=/src/pages/Maz.vue)
To navigate to the example route, click on the Maz list item under Navigation.

**Expected behavior**
It should look the same inside framework7-vue as it does in a vanilla application.

**Screenshots**
<img width="650" alt="Screen Shot 2020-12-07 at 9 10 54 AM" src="https://user-images.githubusercontent.com/736985/101360850-31ea6380-386c-11eb-94de-540c6a0731db.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS8.1]. iOS, Android
 - Browser [e.g. stock browser, safari] Chrome, Safari
 - Version [e.g. 22] latest

**Additional context**

**Comment by jacobg** [comment]
It looks like the following style fixes the issue:
```
.maz-phone-number-input__country-flag {
  width: inherit;
}
```

**Comment by LouisMazel** [comment]
The bug is provided by `framework7-vue`, it add `width: 100%` on all buttons. 

Follow the solution of @jacobg 

Thanks both !
