### ISSUE TITLE
[BUG][<Phone Input> Country list closes when clicking scroll bar inside the MODAL DIALOG]

### ISSUE THREAD

**Issue by paul122297** [LouisMazel/maz-ui#129]
**Describe the bug**
I'm using the phone input inside the MODAL DIALOG on bootstrap-vue, everytime I use the scroll bar the country selection list closes.

**Expected behavior**
The country selection list must not close.

**Desktop:**
 - OS: Windows
 - Browser Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by LouisMazel** [comment]
HI @paul122297,

Can you share a reproduction link ? 

- **[Codesandbox MazPhoneNumberInput Template](https://codesandbox.io/s/mazphonenumberinput-gjfsd?file=/src/App.vue)**
- It only remains to add bootstrap-vue and the modal


Same issue: https://github.com/LouisMazel/maz-ui/issues/113

**Comment by LouisMazel** [comment]
Ok,

I already do the sandbox  ([MazPhoneNumberInput x BootstrapVue](https://codesandbox.io/s/mazphonenumberinput-bootstrapvue-forked-1rpbr?file=/src/App.vue))

I see the bug. I will investigate and I will come back to you

**Comment by paul122297** [comment]
Hi @LouisMazel,

I hope you found the solution for this bug.

Thank you

**Comment by LouisMazel** [comment]
So, after investigating, I don't have any solution for the moment:

There is a conflict between the `blur` event of `<b-modal />`and the `blur` event of `<MazSelect />` (used in `<MazPhoneNumberInput />`)

Why not to use `<MazDialog />` ? I don't have any bug with 
- Documentation: [Enjoy](https://louismazel.github.io/maz-ui/documentation/maz-dialog)

**Comment by paul122297** [comment]
Hello, thank you for assisting me on this issue. I will consider using your MazDialog.

**Comment by paul122297** [comment]
Thank you for suggesting MazDialog. It works as expected now.

**Comment by LouisMazel** [comment]
Nice !

🔥
