### ISSUE TITLE
[QUESTION] Where is maz-ui binary?

### ISSUE THREAD

**Issue by ChaosChild** [LouisMazel/maz-ui#134]
**Describe the bug**
I followed the instruction on how to change colours, etc. of the components here: https://louismazel.github.io/maz-ui/documentation/theme. When I run `npm run get-theme`, I get `sh: 1: maz-ui: not found`

**To Reproduce**
Follow the instruction on https://louismazel.github.io/maz-ui/documentation/theme till you get to "Execute the script".

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome

**Comment by LouisMazel** [comment]
Hi @ChaosChild,

I made a mistake in the documentation. 
Please use `maz get-theme` instead of `maz-ui get-theme`

I will fix it

**Comment by privyreza** [comment]
Tried `npm run  get-theme` but getting 

> maz get-theme

sh: 1: maz: not found

**Comment by LouisMazel** [comment]
@privyreza 

In the 3.x version, the binary does not exist anymore.
You juste have to override the CSS variables: https://louismazel.github.io/maz-ui-3/guide/theme.html

**Comment by privyreza** [comment]
Thanks so much for the response. I can seem to be able to override the variables I tried this:

`:root {
  --maz-bg-color-dark: #FFFFFF !important;
  --maz-bg-color-dark-light: #FFFFFF !important;
  --maz-bg-color-dark-lighter: #FFFFFF !important;
}`

But the component is not changing:
![image](https://user-images.githubusercontent.com/20134879/183453371-a159a2ac-4d9e-4bba-ad0a-597f69b89f20.png)

Here is my inspection:
![image](https://user-images.githubusercontent.com/20134879/183453887-8940bb6b-fd27-4942-a29e-414d0c446636.png)

**Comment by privyreza** [comment]
Ohhh my bad, the issue is now fixed, the override was not working because I was scoping it.

Thanks again
