### ISSUE TITLE
enabling right to left

### ISSUE THREAD

**Issue by MHDuke** [LouisMazel/maz-ui#138]
I have a right to left display via vuetify, when using one of your components, phone number input, it looks awkward. is there a way to enable right to left on your components?

**Comment by LouisMazel** [comment]
Hi @MHDuke, 

I'm not sure to understand what you want. 
It's only for the inputs ? You want writing right to left ?

**Comment by MHDuke** [comment]
the country code component and the phone number component are rendered inversed. the number as well.
![image](https://user-images.githubusercontent.com/37734594/103895244-f0381d00-50a4-11eb-98f8-299a4a6f1c9a.png)
