### ISSUE TITLE
Icon close is broken after build

### ISSUE THREAD

**Issue by alexsonnay** [LouisMazel/maz-ui#144]
<img width="90" alt="image" src="https://user-images.githubusercontent.com/28756458/107642998-e2fae900-6c75-11eb-99b2-46511a37a10b.png">

The icon to clear the input is shown correctly when project is in dev mode. However it's not showing when it's built in production. Only the word "close" is shown instead of the cross.

Info : using Nuxt.js.

**Comment by LouisMazel** [comment]
Hi @alexsonnay ,

You always getting this error ?

**Comment by alexsonnay** [comment]
Hey @LouisMazel 

I never get  this error when `npm run dev`.
But always after `build`.
