### ISSUE TITLE
[BUG][MazPhoneInput] - Cannot read property 'hardwareConcurrency' of undefined

### ISSUE THREAD

**Issue by aaronfessler** [LouisMazel/maz-ui#145]
**Describe the bug**
In some cases with the MazPhone component in Vue, I get:

Reason: TypeError: Cannot read property 'hardwareConcurrency' of undefined

When loading the component.

I am using 2.3.5, Chrome 88.0.4324.

**Comment by LouisMazel** [comment]
Hi @aaronfessler,

Can you share a reproduction link please ? 

No prob for me here: https://codesandbox.io/s/mazphonenumberinput-gjfsd

**Comment by aaronfessler** [comment]
Yes, it is very sporadic and random. I am not able to create a sandbox as a result. I see references to hardwareConcurrency in maz-ui/lib/index.js. Could it be a timing issue of some kind?


<img width="1429" alt="Screen Shot 2021-04-02 at 8 08 17 AM" src="https://user-images.githubusercontent.com/5876531/113414505-24ad3380-938b-11eb-94c1-9a1b6b73577d.png">
