### ISSUE TITLE
[FEATURE] Vue 3 support?

### ISSUE THREAD

**Issue by jacobg** [LouisMazel/maz-ui#147]
Vue 3 support?

**Comment by LouisMazel** [comment]
I don't have any time for the moment... The PR is open : #114 

If you want help me, it's very welcome

**Comment by LouisMazel** [comment]
@jacobg 

The vue 3 version is available,  is still in beta for the moment :

**Getting Started**: https://louismazel.github.io/maz-ui-3/guide/getting-started.html
**MazPhoneNumberInput**: https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input.html

Please note that some things may change in the future.

**Comment by jacobg** [comment]
@LouisMazel That's fantastic! Thanks so much!
