### ISSUE TITLE
[BUG][MazPhoneNumberInput] Error while fetching country code

### ISSUE THREAD

**Issue by aaronfessler** [LouisMazel/maz-ui#151]
Logged 174 crashes with this bug on this line:

`if((e=new p(e)).hasCountry(t))return e.country(t).countryCallingCode();throw new Error("Unknown country: ".concat(t))}function k(t,e){return void 0!==e.countries[t]}function T(t){var e=`

Component props are:
```
{
  "value": "+16159746501",
  "disabled": false,
  "noFlags": true,
  "fetchCountry": ""
}
```

Component is:
	
<MazPhoneNumberInput> at packages/components/MazPhoneNumberInput/_main.vue

**Smartphone (please complete the following information):**
Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1
Landscape orientation
locale en-us

**Additional context**

**Comment by LouisMazel** [comment]
Hi @aaronfessler,

In which country is the app used?

**Comment by LouisMazel** [comment]
Please disable `fetch-country` in this case
