### ISSUE TITLE
Component imports not working

### ISSUE THREAD

**Issue by elev8studio** [LouisMazel/maz-ui#153]
**Describe the bug**
I'm using this package within a Laravel Nova Custom Tool and I'm not able to import any of the individual components in the way described. 

```
import { MazPhoneNumberInput } from 'maz-ui';

Nova.booting((Vue, router, store) => {
  ...
  Vue.component('mobile-number', MazPhoneNumberInput);
});
```

This fails because `MazPhoneNumberInput` is not found or resolvable. Instead the entire maz-ui package is imported, making the JS file 10mb big. 

The component shows just fine on the page.. but it takes about 20 seconds for the page to load. (makes sense why you say on demand option is better.. if it worked...)

**To Reproduce**
1. Fresh Laravel install with Laravel Nova
2. Create Custom Tool for Nova
3. Install maz-ui
4. Import the component in `nova-components/custom-tool-name/resources/js/tool.js`

**Expected behavior**
Just the component I want to import should be imported

**Screenshots**
<img width="665" alt="Screenshot 2021-03-19 at 09 57 03" src="https://user-images.githubusercontent.com/46072213/111765559-683c7380-889c-11eb-98b5-18f157257c21.png">
<img width="482" alt="Screenshot 2021-03-19 at 10 18 49" src="https://user-images.githubusercontent.com/46072213/111765637-84d8ab80-889c-11eb-9ffc-81ad2fc65099.png">
<img width="494" alt="Screenshot 2021-03-19 at 10 22 40" src="https://user-images.githubusercontent.com/46072213/111766136-16481d80-889d-11eb-88ba-163069e46cd3.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 89.0.4389.90

**Comment by LouisMazel** [comment]
@elev8studio 

Do you use the babel configuration ? [Documentation - Babel config](https://louismazel.github.io/maz-ui/documentation/get-started)

Otherwise, you have to import the component and his CSS like that : 

```js
import MazPhoneNumberInput from "maz-ui/lib/maz-phone-number-input";
import "maz-ui/lib/css/base.css";
import "maz-ui/lib/css/maz-phone-number-input.css";
```

--> [codesandbox example](https://codesandbox.io/s/mazphonenumberinput-gjfsd?file=/src/App.vue:367-521)

If you are using multiple components, import the `base.css` file only once
