### ISSUE TITLE
[BUG][<MazPhoneNumberInput>] i can't specify default value

### ISSUE THREAD

**Issue by emrecanmuslu** [LouisMazel/maz-ui#159]
![image](https://user-images.githubusercontent.com/16512073/115148873-2274f580-a06a-11eb-9c2d-232357068782.png)

![image](https://user-images.githubusercontent.com/16512073/115148891-2f91e480-a06a-11eb-83c5-497bf82c3b95.png)

OR

![image](https://user-images.githubusercontent.com/16512073/115148883-299c0380-a06a-11eb-85c2-12d6323994db.png)

Not working?

![image](https://user-images.githubusercontent.com/16512073/115148819-feb1af80-a069-11eb-8f9e-e8f2ec611187.png)

**Comment by Mohammad-Khayat** [comment]
do you fixed it ?
