### ISSUE TITLE
[BUG][<MazPhoneNumberInput>] value cleanup problem

### ISSUE THREAD

**Issue by emrecanmuslu** [LouisMazel/maz-ui#160]
Hi,
After completing the form submission process, I cannot clear it.

![image](https://user-images.githubusercontent.com/16512073/115163538-507e2800-a0b2-11eb-9aed-9c10f293591a.png)

![image](https://user-images.githubusercontent.com/16512073/115163539-56740900-a0b2-11eb-99dd-ffcb359803a4.png)

![image](https://user-images.githubusercontent.com/16512073/115163547-668be880-a0b2-11eb-98c6-a32077e852d2.png)

**Comment by emrecanmuslu** [comment]
@LouisMazel please help me

**Comment by LouisMazel** [comment]
Hi @emrecanmuslu,

You have to use the `v-model`. So you have the `default-phone-number` and the formatted phone number returns by the `v-model`

Please follow this example : [Codesandbox example](https://codesandbox.io/s/mazphonenumberinput-gjfsd?file=/src/App.vue)

**Comment by emrecanmuslu** [comment]
Thank you @LouisMazel 
But when you type the phone number into the sandbox phone input you send, the button does not work, it only clears the button when it is first loaded.

Sorry for my bad english.
