### ISSUE TITLE
[QUESTION] MazPhoneNumberInput max-length

### ISSUE THREAD

**Issue by alekseyburn** [LouisMazel/maz-ui#177]
Hello, how can i to set the max-length to mazPhoneNumberInput? I don't see this option in documentation.

**Comment by LouisMazel** [comment]
Hi @alekseyburn,

The MazPhoneNumberIput uses MazInput and inherits all attributes, so you can: 

```html
<MazPhoneNumberInput
  ref="Phone"
  max-length="8"
  v-model="phoneNumber"
  @update="results = getJson($event)"
/>
```
