### ISSUE TITLE
[BUG][<COMPONENT>]MazPicker, setting size = "sm" does not seem to do anything. How can I make the double calendar more compact?

### ISSUE THREAD

**Issue by roselily8** [LouisMazel/maz-ui#180]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LouisMazel** [comment]
Hi @roselily8,

The size option will change only the size of the input
