### ISSUE TITLE
[BUG][MazPicker] time picker is very sensitive and it change v-model time upon opening

### ISSUE THREAD

**Issue by roselily8** [LouisMazel/maz-ui#181]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LouisMazel** [comment]
Hi @roselily8,

Do you have a video example or a reproduction link with codesandbox for example ?
