### ISSUE TITLE
[BUG][MazPicker]crash on time select with minDate set to 1pm but try to select am crash with error

### ISSUE THREAD

**Issue by roselily8** [LouisMazel/maz-ui#182]
**Describe the bug**
The error message is "TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at findNearestNumberInList (webpack-internal:///./node_modules/maz-ui/lib/maz-picker.js:2301)
    at VueComponent.getAvailableTime" (webpack-internal:///./node_modules/maz-ui/lib/maz-picker.js:4870)

The correct behavior should be to disable the am selection.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LouisMazel** [comment]
Hi @roselily8,

I need more information to fix this bug.

What is the data provided to the component and options set ? 
Do you have a video example or a reproduction link with codesandbox for example ?

**Comment by LouisMazel** [comment]
Solved in v3.x
