### ISSUE TITLE
Clear event on MazPicker

### ISSUE THREAD

**Issue by alexauvray** [LouisMazel/maz-ui#185]
Is it possible to add a clear event on MazPicker ?

**Comment by LouisMazel** [comment]
Hi @alexauvray, 

Done on [2.3.10](https://github.com/LouisMazel/maz-ui/releases/tag/v2.3.10) version :)

**Comment by alexauvray** [comment]
Thanks! However you wrote "clear" in your doc, while it's "clearable".
