### ISSUE TITLE
[BUG][MazPhoneNumberInput] Searching country code with "+" shows no results

### ISSUE THREAD

**Issue by alrayyes** [LouisMazel/maz-ui#191]
**Describe the bug**
Inputting a "+" before country number causes no results to be shown

**To Reproduce**
1. Input "+44" into country code select box

**Expected behavior**
Country code for UK to be selected

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 95

**Additional context**

**Comment by LouisMazel** [comment]
Hey @alrayyes,

This issue is solved in [v3.0.11](https://github.com/LouisMazel/maz-ui/releases/tag/v3.0.11)

Enjoy
