### ISSUE TITLE
[FEATURE] MazPicker Format 24h

### ISSUE THREAD

**Issue by neopheus** [LouisMazel/maz-ui#192]
Hi,

currently only the 12h (am/pm) format is available

![chrome_HtOZlFf5SS](https://user-images.githubusercontent.com/5160844/151781031-3b14b205-c9c1-41b7-8162-c5984f2f700c.png)

it would be interesting to have the possibility to choose the 24h format

Thx

**Comment by LouisMazel** [comment]
Hello @neopheus,

You can do it by change the input format : 

```vue
<template>
  <MazPicker v-model="date" format="DD-MM-YYYY HH:mm" />
</template>

<script>
  import MazPicker from 'maz-ui/lib/maz-picker'
  export default {
    components: { MazPicker },
    data() {
      return {
        date: undefined
      }
    }
  }
</script>
```

**According with [MomentJS](https://momentjs.com/)**

`hh` or `h` is 12h format
`HH` or `H` is 24h format
