### ISSUE TITLE
MazBtn icon not working

### ISSUE THREAD

**Issue by christianzimmermann** [LouisMazel/maz-ui#24]
According to the docs there is an icon property (the doc might not be correct since the type is given as a boolen).

The icon is not appearing in the button:

`                <MazBtn icon="login" block type="submit">Login</MazBtn>
`

Since all the example buttons are also without icons, that is a feature in progress?

Great library! Thanks for the awesome work
Cheers 
Christian

**Comment by LouisMazel** [comment]
@christianzimmermann 

Indeed the feature is not yet supported, it's in progress, it should not be in the doc.
I will add this feature first and I will come back to you

Thanks for your feedback !

**Comment by LouisMazel** [comment]
Hi, 

I released the version 1.2.0 and icons options are now available :fire:

- [Btn documentation](https://louismazel.github.io/maz-ui/#/documentation/btn) - Show the "Icon" section with code example
- [Release detail](https://github.com/LouisMazel/maz-ui/releases/tag/1.2.0)

Enjoy
