### ISSUE TITLE
[FEATURE] is there a way to access libphonenumber-js from MazUi?

### ISSUE THREAD

**Issue by shidcordero** [LouisMazel/maz-ui#246]
**Is your feature request related to a problem? Please describe.**
I am trying to implement VeeValidate on my Nuxt App and I'm extending a custom rule which I need to check if the phone is valid or not. Since I cannot pass the IsPhoneValid in VeeValidate rules, is there a way that I can use parsePhoneNumberFromString of libphonenumber-js from MazUi?

**Describe the solution you'd like**
A way to import libphonenumber-js to use parsePhoneNumberFromString

**Comment by LouisMazel** [comment]
Hi @shidcordero 

Which version do you use for ? 
- vue
- maz-ui
- vee-validate

Have some code for:
- vue@2
- maz-ui@2
- vee-validate@3

You can use this validation rules :

`**/rules/phone-number.ts`

```ts
import examples from 'libphonenumber-js/examples.mobile.json'
import { parsePhoneNumberFromString, getExampleNumber, CountryCode } from 'libphonenumber-js'
import { ValidationRule } from 'vee-validate/dist/types/types'

export const phone: ValidationRule = {
  validate: (value, args) => {
    const countryCode = Array.isArray(args) ? args[0] : undefined

    if (!countryCode) {
      throw new Error('A country code must be specified (e.g phone:FR).')
    }

    if (!value) {
      return false
    }

    const parsing = parsePhoneNumberFromString(value, countryCode as CountryCode)

    return parsing?.isValid() ?? false
  },

  message: (field, args) => {
    const countryCode = args[0]

    if (!countryCode) {
      throw new Error('A country code must be specified (e.g phone:FR).')
    }

    /**
     * Get the phone number example to pass to the
     * translation key.
     */
    const phoneNumber = getExampleNumber(countryCode, examples)

    const example = phoneNumber?.formatNational() ?? undefined

    const message = example
        ? 'Phone number is invalid. Example: {example}'
        : 'Phone number is valid'
      {
        field,
        example,
      },
    ) as string

    return message
  },
}
```

Up to you to translate it for **vee-validate@4** if it's necessary 

Good for you ? If you need more explanation, ask me

**Comment by shidcordero** [comment]
works great. Thanks!
