### ISSUE TITLE
[Issue][MazPhoneNumberInput] Country list hiding doesn't work

### ISSUE THREAD

**Issue by vladkolotvin** [LouisMazel/maz-ui#257]
You can open country list by click on down arrow. But click on up arrow doesn't close it.

**Comment by LouisMazel** [comment]
Hi @vladkolotvin,

It's a normal behavior. 
I want the same behavior as the native HTML `<select />`

You can close the component only when you choose a value or you blur the component: https://developer.mozilla.org/fr/docs/Web/HTML/Element/select

**Comment by vladkolotvin** [comment]
I'm using firefox and native select can be closed by click on a default value
https://user-images.githubusercontent.com/768260/167851426-3554f7e2-7033-478a-bfec-5f86e0778e44.mov

**Comment by LouisMazel** [comment]
You not clicking on the input but on the empty option in the list. 

May be I will developing this feature but I'm not sûre
