### ISSUE TITLE
[Issue][<COMPONENT>]

### ISSUE THREAD

**Issue by hathemi** [LouisMazel/maz-ui#259]
![Sans titre](https://user-images.githubusercontent.com/23275040/167389610-888ae282-7d0c-47b4-9d21-836a293f76e7.png)
i'm using vuejs/javascript. i want to use translations options but it doesn't work! i still get the default labels.
i'm using "maz-ui": "^3.0.0-beta.18" version
any help please !!!

**Comment by hathemi** [comment]
```
          :translations="{
              countrySelector: {
                placeholder: 'Code pays',
                error: 'Choisir un pays',
                },
              phoneInput: {
                placeholder: 'Numéro de téléphone',
                example: 'Exemple :'
               }
               }"
```
i have fixed it using this code instead.

**Comment by LouisMazel** [comment]
Hi @hathemi,

Yes, you can follow the documentation here: https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input.html#translations
