### ISSUE TITLE
[BUG][<MAZPicker>] Clicking the open button sends form

### ISSUE THREAD

**Issue by ruben2m** [LouisMazel/maz-ui#315]
**Describe the bug**
When I click the open button to show the months, the buttons acts as submit button.

**Expected behavior**
It should be type="button"

**Comment by LouisMazel** [comment]
Hi @ruben2m,

I released the 3.0.2 to fix this behavior ! 

**[Release 3.0.2](https://github.com/LouisMazel/maz-ui/releases/tag/v3.0.2)**

Thanks for your report !
