### ISSUE TITLE
Country code is displayed twice

### ISSUE THREAD

**Issue by alexsonnay** [LouisMazel/maz-ui#32]
Hey !

Country code is displayed twice in fields that are near to each other, which seems like a duplicate information :
- country code field 
- phone number field

example from your doc (https://louismazel.github.io/maz-ui/#/documentation/phone-number-input) :

+33 / +33 65 65 65 65

Is there a way to remove it from the phone number field so that it's not displayed twice ?

**Comment by LouisMazel** [comment]
Hi @alexsonnay,

Same thing like the #33 

I will show the good format in the input. 
Follow this PR: https://github.com/LouisMazel/maz-ui/pull/34

Thank you

**Comment by LouisMazel** [comment]
Hi, 

I released the version 1.2.0 and it's fixed :fire:

[Release detail](https://github.com/LouisMazel/maz-ui/releases/tag/1.2.0)
