### ISSUE TITLE
[BUG][<MazCheckbox>] Multiple checkboxes in component only updates one v-model

### ISSUE THREAD

**Issue by TeeDeL** [LouisMazel/maz-ui#321]
**Describe the bug**
When having more than one checkbox within a component, even when assigning different v-models, when selecting any of the checkboxes it sets the value for only one v-model

**To Reproduce**

1. Create component
2. Add 2 or more MazCheckbox
3. Set 2 different v-models
4. Error: clicking any other checkbox sets the value for 1st value

**Expected behavior**
Able to set the value of the v-model assigned to component

**Screenshots**
(This was after clicking "Flag 2" checkbox)
![image](https://user-images.githubusercontent.com/47976956/182872557-05584131-a3ea-4ac6-bb6a-73d08052d09d.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version:  103.0.5060.114

**Additional context**
Basic code sandbox to demonstrate:
https://codesandbox.io/s/suy8bf

I initially came across this when using a v-for on an array of objects and assigning the v-model that way and thought that was the issue but seem present even when using basic values

**Comment by LouisMazel** [comment]
Hi @TeeDeL,

To fix it, you just have to add an id on each input: 

```html
<template>
  <MazCheckbox v-model="flag1" id="flag1">Flag 1</MazCheckbox>
  <MazCheckbox v-model="flag2" id="flag2">Flag 2</MazCheckbox>
</template>
```

But, I will release a new version (3.0.2) to generate an uniq id for each instance of component

Thanks for your report !

**Comment by LouisMazel** [comment]
The 3.0.2 version is released !

**Comment by TeeDeL** [comment]
@LouisMazel absolutely amazing! I assumed we didn't need an id based on the documentation but I guess for 3.0.2 now we don't need it 😅 Thank you for your work
