### ISSUE TITLE
What is the event for "clear" button ?

### ISSUE THREAD

**Issue by alexsonnay** [LouisMazel/maz-ui#33]
I didn't find the event name in your doc for the "clear" button.

I tried @clear but it's not working. 

What is it ?

**Comment by LouisMazel** [comment]
Hi @alexsonnay,

I will add the support of `clear` event in the next version. 

You can follow this PR: https://github.com/LouisMazel/maz-ui/pull/34

I'll keep you posted as soon as it's released

Thanks for your feedback

**Comment by LouisMazel** [comment]
Hi, 

I released the version 1.2.0 and I added `clear` event for **maz-phone-number-input**

[Release detail](https://github.com/LouisMazel/maz-ui/releases/tag/1.2.0)
