### ISSUE TITLE
[Issue][MazPhoneInput]

### ISSUE THREAD

**Issue by privyreza** [LouisMazel/maz-ui#344]
**The plugin doesnt work with any multi-select vue plugin**
The phoneinput is set to read only whenever you are using `https://github.com/vueform/multiselect` or any other multiselect vue plugin

**To Reproduce**

1. Install maz-ui and configure it
2. Install `https://github.com/vueform/multiselect` and configure it
3. Create a form with both MazPhoneInput and Multiselect components

**Expected behavior**
The MazPhoneInput should continue to work

**Desktop (please complete the following information):**

- OS: [Ubuntu 22]
- Browser [Chrome]
- Version [Version 104.0.5112.79 (Official Build) (64-bit)]

**Comment by LouisMazel** [comment]
Hi @privyreza 

Can you provide a reproduction link please ? 
You can fork this codesandbox base: https://codesandbox.io/s/maz-ui-3-base-ov0os7?file=/src/App.vue

Thanks
