### ISSUE TITLE
[BUG][MazPhoneNumberInput] Country selector not focusing when clicking on arrow

### ISSUE THREAD

**Issue by kenndox** [LouisMazel/maz-ui#354]
**Issue description**
The country selector in the phone number input does not focus input if opened with the dropdown arrow.

In the maz-ui-v2 version the input focused correctly even if you used the dropdown arrow to open the country selector, but in the 3.0 version this no longer seems to be the case.

**To Reproduce**
Click on the arrow in the country selector to open dropdown

**Expected behavior**
Country dropdown focused, allowing the user to type to search countries

**Comment by LouisMazel** [comment]
Hi @kenndox,

I'm not sure to understand what you mean. 
Have you a video or GIF to show me what's the bug please ?

Thanks

**Comment by kenndox** [comment]
Hey @LouisMazel ,

I recorded a short video on your documentation page: 

https://user-images.githubusercontent.com/20651235/191275676-0bba1b78-766d-4750-9408-94eddad88bb9.mp4

As you can see, clicking inside the selector allows me to type to search for countries, but if I click on the arrow, the input is not focused and typing does nothing.

**Comment by LouisMazel** [comment]
Thanks a lot ! 
It's clear for me now, I will fix it. 

I keep you in touch when it's ok

**Comment by LouisMazel** [comment]
@kenndox The new version v3.0.5 is released with the bug fix :)

**Comment by kenndox** [comment]
@LouisMazel Hey, just installed v3.0.5 and can confirm it works :)

Thanks a bunch!
