### ISSUE TITLE
[FEATURE][MazPhoneNumberInput] Non-floating labels

### ISSUE THREAD

**Issue by antonioliv** [LouisMazel/maz-ui#357]
**Is your feature request related to a problem? Please describe.**
As an integrator I want the possibility to customize the labels for the inputs. Choosing between floating labels or non-floating labels (external to the input).

**Describe the solution you'd like**
Adding a component prop to indicate if the labels should be floating or above the input.

**Describe alternatives you've considered**
The alternative to workaround this was to manipulate the DOM tree with JS. 

**Additional context**
<img width="495" alt="Captura de ecrã 2022-09-23, às 10 59 16" src="https://user-images.githubusercontent.com/30448483/191937105-b3692f1f-b68e-4951-ae26-2819f7cf83af.png">

**Comment by LouisMazel** [comment]
Hey @antonioliv,

Your request it's a big change for the UI. 
I'm not sure I want to implement this feature and the HTML structure is not ready without big changes.

May be you can create a component to wrap this component and add the floating labels !?
