### ISSUE TITLE
[Issue] Maz Picker

### ISSUE THREAD

**Issue by emg36** [LouisMazel/maz-ui#359]
**Describe the bug**
It's similar to #57. If the v-model value is null then the picker won't render

**To Reproduce**
```
<template>
  <MazPicker
    v-model="pickerValue"
  />
</template>

<script>
  import MazPicker from 'maz-ui/components/MazPicker';
  export default {
    components: { MazPicker },
    data () {
      return {
        pickerValue: null
      }
    }
  }
</script>

```
The error I get

<img width="596" alt="CleanShot 2022-09-29 at 14 14 14@2x" src="https://user-images.githubusercontent.com/5077135/192916354-2d01cba7-7a0c-4445-a4e5-96c2e0689f3d.png">

It does however work if pickerValue is undefined.

**Expected behavior**
I would expect the date/time picker to render with no value similar to how the undefined or and empty string would behave.

**Comment by LouisMazel** [comment]
Hey @emg36,

I found the bug, I will fix it in the next patch version. 
I keep you in touch here when it's released. 

Thanks for your feedback

**Comment by LouisMazel** [comment]
The [v3.0.6](https://github.com/LouisMazel/maz-ui/releases/tag/v3.0.6) version is released and fixes the bug!

Thanks again @emg36 !
