### ISSUE TITLE
[FEATURE][MazSelect] - Add Search options.

### ISSUE THREAD

**Issue by enmanuel97** [LouisMazel/maz-ui#363]
I think that this component needs a search options

**Comment by LouisMazel** [comment]
Hey @alrayyes,

Feature available in [v3.0.11](https://github.com/LouisMazel/maz-ui/releases/tag/v3.0.11)

Use the `search` property

```vue
<template>
  <MazSelect v-model="selectValue" :options="[{ ... }]" search />
</template>
```

Enjoy 🔥
