### ISSUE TITLE
input for textarea is missing 

### ISSUE THREAD

**Issue by raymond-digi** [LouisMazel/maz-ui#364]
textarea input is available in v2 .
but not able to find it in v3.
have any plans on it?

**Comment by LouisMazel** [comment]
Hi @raymond-digi,

I just released a new textarea component in v3.0.8: 
- Documentation: https://louismazel.github.io/maz-ui-3/components/maz-textarea.html
- Release: https://github.com/LouisMazel/maz-ui/releases/tag/v3.0.8

Enjoy
