### ISSUE TITLE
Required is not working on Select field

### ISSUE THREAD

**Issue by professorhaseeb** [LouisMazel/maz-ui#372]
Code:

`<MazSelect v-model="state" :options="options" required />`

![image](https://user-images.githubusercontent.com/1492888/200584734-f047f78e-6dcf-4160-ab73-2d6f13e54bab.png)

**Comment by LouisMazel** [comment]
I just released a new version (v3.3.2) to fix it

- [release detail v3.3.2](https://github.com/LouisMazel/maz-ui/releases/tag/v3.3.2)
- [Changelog](https://github.com/LouisMazel/maz-ui/blob/master/packages/lib/CHANGELOG.md)
