### ISSUE TITLE
[FEATURE] Toast should appear above overlay

### ISSUE THREAD

**Issue by paulvonber** [LouisMazel/maz-ui#436]
Toast appears under the Dialog overlay, so if it's needs to be show while dialog is opened, that's not really possible at the moment.

I would suggest to increase z-index by default or at least make it as an option.

**Comment by LouisMazel** [comment]
Hey @paulvonber,

It's fixed in v3.4.1 : 
- [Release Changelog](https://github.com/LouisMazel/maz-ui/releases/tag/v3.4.1)

Enjoy !
