### ISSUE TITLE
[FEATURE] Way to edit component styles?

### ISSUE THREAD

**Issue by przzz27** [LouisMazel/maz-ui#457]
**Is your feature request related to a problem? Please describe.**
This is not related to an existing problem, might not be a problem but an oversight on my part, looking for advice.

**Describe the solution you'd like**
I would like to edit the styles for [PhoneNumberInput](https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input) so country input can use a width i provide instead of being fixed to 148px

**Describe alternatives you've considered**

- Use [theming](https://louismazel.github.io/maz-ui-3/guide/theme), the problem i see is that the class property i need to change does not appear there, and i am not sure if the theme is exclusive for colors or if it also applies to other classes such as `m-phone-number-input__select`

- Adding !important keyword with a custom width for the class i need to change eg; ``<style>
.m-phone-number-input__select {
  width: 110px !important;
}
</style>``

**Additional context**
Component does not look right in smaller sizes
<img width="540" alt="Screen Shot 2022-12-13 at 10 23 12" src="https://user-images.githubusercontent.com/61523021/207414548-fab1d07e-1173-418c-889f-3d145bcf7f69.png">

**Comment by LouisMazel** [comment]
Hey @przzz27,

No options are provided to custom the width of the country input. CSS variables of theme is only for global rules.

So, yes you have to override the CSS in this case. 

You can override this rules in a scoped style :

```vue
<style scoped>
.your-root-class:deep(.m-phone-number-input .m-select.m-phone-number-input__select) {
    width: 110px;
}
</style>
```

The component is good with small screens (see example on my iPhone Mini). 
I think you shouldn't set the component in column in small size. The component and user need space.

![IMG_5445](https://user-images.githubusercontent.com/12446546/207473885-a7a90b73-1261-40b9-94cc-457fc736de77.jpg)

**Comment by LouisMazel** [comment]
# Bonus

For the component match style of your other input, you can override these CSS variables :

```css
:root {
  --maz-border-width: 0.125rem; /* maybe use 1px */
  --maz-border-radius: 0.5rem; /* reduce this value */
}
```

**Comment by przzz27** [comment]
Souds reasonable, thanks for the input!
