### ISSUE TITLE
[Issue]MazSelect not working for Nuxt 3

### ISSUE THREAD

**Issue by typhoon11** [LouisMazel/maz-ui#468]
**Describe the bug**
MazSelect component is not working on Nuxt V3. When using MazSelect the options dropdown is not coming and instead just giving a Input Box

**Expected behavior**
The select menu dropdown should open upon clicking 

**Screenshots**
![image](https://user-images.githubusercontent.com/66431066/208348241-802ead79-e7c6-4cc4-b164-cf8bf700fbd9.png)

**Desktop (please complete the following information):**

- OS: Windows OS
- Browser: Brave
- Version: 1.46.144

**Additional context**
Here is the bug reproduction in stackblitz : https://stackblitz.com/edit/github-sssh48-zhwbjr?file=app.vue

**Comment by LouisMazel** [comment]
@typhoon11 
Hey!

I you did a little mistake in your import path.

Use MazSelect at the and not MazInput
