### ISSUE TITLE
How to add Nuxt's useFetch data directly in options of MazSelect?

### ISSUE THREAD

**Issue by typhoon11** [LouisMazel/maz-ui#469]
I am fetching an array of data from my api and want them as options to the MazSelect but it says options are null, so how we can do that? I am using the Nuxt 3's `useLazyFetch` to fetch the data.

**Comment by LouisMazel** [comment]
Hey @typhoon11,

Yes, to work, the component needs options.

You have multiple options to do it: 

1 - Render the component with you have data

```vue
<template>
  <MazSelect v-if="!pending" :options="options" />
  <!-- or -->
  <MazSelect v-if="options" :options="options" />
<template>

<script lang="ts" setup>
  const { pending, data: options } = useLazyFetch('/api/options')
<script>
```

2 - Initialize your MazSelect with an empty array

```vue
<template>
  <MazSelect :options="computedOptions" />
<template>

<script lang="ts" setup>
  import { computed } from 'nuxt'
  const { data: options } = useLazyFetch('/api/options')
  
  const computedOptions = computed(() => options ?? [])
  // or const computedOptions = computed(() => options.value ?? []) if it's a Ref returned
<script>
```

3 - SSR request - Get options on server side (from the page component) and render the page when you have the data
