### ISSUE TITLE
Ability to set the theme dynamically. In my application I have a night and sunny mode that requires dynamically setting of the dark mode. [FEATURE]

### ISSUE THREAD

**Issue by akatebi** [LouisMazel/maz-ui#472]
**Is your feature request related to a problem? Please describe.**
I am using Vuetify version-3 I would like the user to switch between dark, and light themes. I am using a few components from  maz-ui but your dark setting is in the root html tag in the index.html file. It is not dynamic.
This is your documentation link: https://louismazel.github.io/maz-ui-3/guide/dark-mode

Basically I would like to change the theme at runtime.

**Comment by LouisMazel** [comment]
As you can see in the tip section,  you can use the composable "useThemeHandler to do it

https://louismazel.github.io/maz-ui-3/composables/use-theme-handler

**Comment by LouisMazel** [comment]
I just released a new version [v3.6.7](https://github.com/LouisMazel/maz-ui/releases/tag/v3.6.7) with two new methods in the composable : `setDarkTheme` & `setLightTheme` to give you more control on the using theme !

Check the doc: [useThemeHandler](https://louismazel.github.io/maz-ui-3/composables/use-theme-handler)
