### ISSUE TITLE
MazCard : is there a way to disable the Popup that comes up when you click on a card image ?

### ISSUE THREAD

**Issue by Timothy16** [LouisMazel/maz-ui#482]

**Comment by LouisMazel** [comment]
Hey @Timothy16,

What pop-up do you mean? 

This one ? 
![image](https://user-images.githubusercontent.com/12446546/212772858-6d7b2382-7510-4372-a3f3-7e0e33986ab6.jpeg)

**Comment by Timothy16** [comment]
Yes

**Comment by LouisMazel** [comment]
By default this pop-up is disabled

Do you use ´zoom´ attribut/prop on the component?
You shouldn't

**Comment by Timothy16** [comment]
i didn't use the zoom props

<template>
  <MazCarousel>
    <template #title>
      <h4 class="maz-m-0">Carousel</h4>
    </template>
    <MazCard
      v-for="(item, i) in Array(8)"
      :key="i"
      :images="[
        'https://placekitten.com/250/300'
      ]"
      style="min-width: 250px;"
    >
      <template #title>
        <h4 class="maz-m-0">
          Steven Seagal
        </h4>
      </template>
      <template #content>
        <p class="maz-text-muted" style="margin-bottom: 0;">
          You're awesome! You're awesome!
        </p>
      </template>
    </MazCard>
  </MazCarousel>
</template>

**Comment by LouisMazel** [comment]
Ok, I will check

**Comment by Timothy16** [comment]
Hi @LouisMazel , any update on this issue ?

**Comment by LouisMazel** [comment]
@Timothy16 It's fixed in the new version released: v3.6.10

Enjoy :)

**Comment by Timothy16** [comment]
Great Job @LouisMazel
