### ISSUE TITLE
MazDialogPromise use html tags in message property

### ISSUE THREAD

**Issue by malikdoksoz** [LouisMazel/maz-ui#484]
**MazDialogPromise**
How to use html tags in message content?
![Ekran Resmi 2023-01-26 16 27 37](https://user-images.githubusercontent.com/26676061/214861227-3e1869d0-9e39-4657-ae0f-23697a444953.png)

**Comment by LouisMazel** [comment]
Can you provide a reproduction link with codesandbox or something like that ? You can also show me your code implementation here

**Comment by malikdoksoz** [comment]
You can try.Html code is not used (message and title)

**Comment by LouisMazel** [comment]
I don't understand. What's `try.html` ? Please be more clear, I can't help you.

**Comment by malikdoksoz** [comment]
Oh thank you for quick reply

**Comment by LouisMazel** [comment]
You're welcome :)
