### ISSUE TITLE
[insecure request to ipwho.is]<MazPhoneNumberInput>

### ISSUE THREAD

**Issue by GregCoyle-1** [LouisMazel/maz-ui#486]
The MazPhoneNumberInput component uses an insecure http://ipwho.is request to fetch the current country when the `fetch-country` prop is set to true. If the component is set up in an environment that's already using a secure https then the request can be blocked with a `Mixed Content` error. Specifically in Chrome v109.0.5414.120, the console error reads _"Mixed Content: The page at 'https://blahblahblah.com/' was loaded over HTTPS, but requested an insecure resource 'http://ipwho.is/'. This request has been blocked; the content must be served over HTTPS."

**To Reproduce**
Steps to reproduce the behavior: See description above

**Expected behavior**
If you change the request to a secure https://ipwho.is that should solve the issue

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome 109.0.5414.120

**Comment by LouisMazel** [comment]
Hi @GregCoyle-1, 

I just released the v3.7.0. 
Now the component the secure URL :) 

Enjoy
