### ISSUE TITLE
MazDialog width

### ISSUE THREAD

**Issue by Timothy16** [LouisMazel/maz-ui#491]
In mazDialog v2, the width of the dialog box can be adjusted and also an overflow-y in the case of long text. But it seems this features are not available in v3.
Can this feature be made available please

**Comment by LouisMazel** [comment]
Hi @Timothy16, 

I just released the v3.7.0. 
Now the component MazDialog has `width`, `max-width`, and `wrapperClasses` props options.

Props documentation: https://louismazel.github.io/maz-ui-3/components/maz-dialog#props

Enjoy

**Comment by Timothy16** [comment]
I'm trying to install the v3.70, but getting an npm error that version is not found

**Comment by LouisMazel** [comment]
The package version should be available now: https://www.npmjs.com/package/maz-ui?activeTab=versions

If it's not the case, wait a few minutes

**Comment by Timothy16** [comment]
![image](https://user-images.githubusercontent.com/55112043/223214665-761870fb-7d86-4271-a2d0-45dea515988a.png)
The component doesn't have overflow-y 
It doesn't fit to screen when you have more content on the dialog

**Comment by Timothy16** [comment]
<img width="881" alt="Capture" src="https://user-images.githubusercontent.com/55112043/223215483-1ab2e10f-2c50-4308-98f9-0b6b45465ef5.PNG">
The component doesn't fit to screen when you have more content to display on the the dialog box, an overflow-x should be added

**Comment by LouisMazel** [comment]
I added `scrollable` and `max-heigth` props options for the MazDialog component in the **[v3.7.1](https://github.com/LouisMazel/maz-ui/blob/master/packages/lib/CHANGELOG.md)**

See the section "Scrollable" in the documentation: https://louismazel.github.io/maz-ui-3/components/maz-dialog#scrollable
