### ISSUE TITLE
[Issue][MazPhoneNumberInput] Bad Lithuanian number formating

### ISSUE THREAD

**Issue by eimaz5** [LouisMazel/maz-ui#501]
*Describe the bug*
When I select Lithuania country, and enter e.g. +37061111112, input fields shows (8-611) 11112, but it should show 611 11112
The phone value is coming from the backend and is +37061111112

*To Reproduce*

1. Select Lithuania
2. Enter 61111112

*Expected behavior*
Input field should show 611 11112

*Screenshots*
![image](https://user-images.githubusercontent.com/17913733/224121657-809143fa-fe52-45fb-a672-660c869a3c1c.png)

*Additional context*
maz-ui: 3.7.1
libphonenumber-js: 1.0.21

**Comment by LouisMazel** [comment]
This format is provided by `libphonenumber-js`, I can't change it but I will add an option to disable auto-formatting. 

Follow this issue instead: https://github.com/LouisMazel/maz-ui/issues/655
