### ISSUE TITLE
[Issue][<MazPicker>]

### ISSUE THREAD

**Issue by zest97** [LouisMazel/maz-ui#502]
**Describe the bug**
When I try to use DatePicker component using example provided by documentation, get the following error.
`The requested module '/_nuxt/node_modules/dayjs/plugin/customParseFormat.js?v=xxxx' does not provide an export named 'default'`

```
// DatePicker.vue
<template>
  <MazPicker v-model="dateValue" label="Select date" color="secondary" />
</template>

<script setup lang="ts">
import MazPicker from 'maz-ui/components/MazPicker'
import { ref } from 'vue'
const dateValue = ref('2022-02-03')
</script>
```

**To Reproduce**
nuxt produce error on using above example component.

nuxt-version: 3.2.3
dayjs: 1.11.7
maz-ui: 3.7.1

**Comment by LouisMazel** [comment]
Hi @zest97,

I can't reproduce this bug. it's still present? 

I tested with codesandbox, no bug appears: https://codesandbox.io/p/sandbox/maz-ui-3-x97mxk

**Comment by Timothy16** [comment]
This error still exist

**Comment by LouisMazel** [comment]
Can send me a reproduction link with codesandbox, stackblitz or whatever please? 
I can't reproduce it.
