### ISSUE TITLE
[FEATURE] Phone Number Format Update for Hong Kong

### ISSUE THREAD

**Issue by kempeslee** [LouisMazel/maz-ui#504]
**Is your feature request related to a problem? Please describe.**
Hong Kong phone numbers must always be 8 digits. eg +852 XXXX XXXX
**Describe the solution you'd like**
When you start a phone number with 9 then it allows fewer than 8 digits, eg: +852 9456 789 or +852 945678

**Describe alternatives you've considered**

**Additional context**

**Comment by LouisMazel** [comment]
Solved in v3.20.0
