### ISSUE TITLE
[Issue] General css style issue

### ISSUE THREAD

**Issue by Petrychyn** [LouisMazel/maz-ui#530]
**Describe the bug**
All of the style rules in [reset.css](https://github.com/LouisMazel/maz-ui/blob/2789a27eabe574f29159a302122022cc66f6b9a2/packages/lib/package/css/reset.css) are overly broad, applying (for example) a border to everything (`*`), and font-size and line-height to all `button`, `input`, etc. These rules should be scoped to only apply to the components coming from this library, or these rules should not be included in the bundled `main.css` that is included with the library. The result is, for example, an un-styled `<textarea/>` loses the default border provided by the browser's stylesheet.

**To Reproduce**

1. Include maz-ui's `main.css` file as described in [Getting Started](https://louismazel.github.io/maz-ui-3/guide/getting-started)
2. Include an un-styled `<textarea/>`.
3. Observe the textarea has no border.

**Expected behavior**
The textarea should have a border as defined by the browser's default stylesheet.

**Comment by LouisMazel** [comment]
Hi,

I understand but these rules are applied by TailwindCSS and it's a normal behavior. 
For an UI Library, resetting all default/native CSS rules of browsers is a good practice. It's too difficult to apply a reset CSS for each component.

You can test with the famous library Vuetify in this codesandbox: https://codesandbox.io/p/sandbox/pensive-snowflake-wyqg92. All CSS rules are overridden too.
