### ISSUE TITLE
Search translation to MazPhoneNumberInput

### ISSUE THREAD

**Issue by Domenys** [LouisMazel/maz-ui#543]
Could you please add to props transactions the ability to add a translation for the placeholder of the search field? At the moment, it is possible to add a translation for all text, except for the search placeholder.

**Comment by LouisMazel** [comment]
Hi @Domenys,

It's missing in the documentation but you can already use: 

```vue
<template>
  <MazPhoneNumberInput
    :translations="{
      countrySelector: {
        searchPlaceholder: 'Search placeholder',
      },
    }"
  />
</template>
```

I will add it in the documentation soon
Thanks
