### ISSUE TITLE
[MazInuputTag cross button not rendering](https://louismazel.github.io/maz-ui-3/components/maz-input-tags)

### ISSUE THREAD

**Issue by typhoon11** [LouisMazel/maz-ui#551]
**Describe the bug**
When the MazInputTag component is used the cross button beside the tag is not rendering, the div class for the button is rendering but the svg is not coming.

**To Reproduce**
Use the MazInputTags in Nuxt 3.6

**Expected behavior**
The cross button should render

**Screenshots**
![image](https://github.com/LouisMazel/maz-ui/assets/66431066/1c605818-c840-4ff9-9994-910d7d3a03e4)
![image](https://github.com/LouisMazel/maz-ui/assets/66431066/5e156ce0-0daf-487c-9c47-5ee70e5d0a36)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Brave

**Comment by LouisMazel** [comment]
Hi @LouisMazel,

The bug should be solved in v3.10.0. 
Can you check it and give me your feedback?

Thanks
