### ISSUE TITLE
[BUG] MazPicker doesn't work

### ISSUE THREAD

**Issue by disjointed** [LouisMazel/maz-ui#57]
**Describe the bug**
Hello again!
The `MazPicker` component doesn't work -- it errors on mount.

**To Reproduce**
Here's example from the docs:
```
<template>
  <MazPicker
    v-model="pickerValue"
  />
</template>

<script>
  import { MazPicker } from 'maz-ui'
  export default {
    components: { MazPicker },
    data () {
      return {
        pickerValue: null
      }
    }
  }
</script>
```
I'm using `Nuxt`, so I create a new page and put this code in it. Then, when I hit `ctrl+s` the server rebuilds just fine, but in browser there is the following error: `this.$options.filters.capitalize is not a function`.

**Expected behavior**
Component expected to not crash my `Nuxt` project :)

**Screenshots**
It just shows the standard `Nuxt` error page with the following content:
```
TypeError
**this.$options.filters.capitalize is not a function**
```
and request details, headers, cookies, etc.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (latest version)
 - Version: latest (83)

**Additional context**
It seems that the component uses some `Vue`-filter, that isn't present in production, but maybe I'm wrong.

**Comment by LouisMazel** [comment]
Thanks again for your feedback ! :) 

It's fixed on the release branch: https://github.com/LouisMazel/maz-ui/pull/54/commits/9efeea450649bc49f35c76522af892bae8cf2e4a

It's will be available on the next version

**Comment by LouisMazel** [comment]
The 1.2.3 version is released 

RELEASE: https://github.com/LouisMazel/maz-ui/releases/tag/v1.2.3
