### ISSUE TITLE
[Issue][MazPicker] First day of week not working in some timezones

### ISSUE THREAD

**Issue by EduardMartiVaquer** [LouisMazel/maz-ui#572]
Recently i've noticed that when outside of europe, even if I set the first day of week to 1 for the ui picker, the first day still is set to sunday. If I don't set the day, then it says saturday. The thing is that this only affects the header of the week, the numbers seem to be working fine
<img width="303" alt="Captura de pantalla 2023-08-02 a las 9 19 14" src="https://github.com/LouisMazel/maz-ui/assets/14188876/425b1d03-2839-4304-b7a4-9c6c6d0264d5">
As you can see, it starts at sunday but August 2nd appears to be where wednesday should be.

**Comment by LouisMazel** [comment]
Hi @EduardMartiVaquer,

Thanks for the feedback; I will fix it soon, no date for the moment, I'm a bit busy.
You or others can create a PR for this !

**Comment by LouisMazel** [comment]
Bug fixed in v3.19.1

Changelog: https://github.com/LouisMazel/maz-ui/releases/tag/v3.19.1
