### ISSUE TITLE
[BUG][MazPicker] Console warnings

### ISSUE THREAD

**Issue by disjointed** [LouisMazel/maz-ui#59]
**Describe the bug**
Referencing the issue #57 I wanted to say -- thank you, `MazPicker` now works just fine! But there are some warnings in browser's console when you use it.

**To Reproduce**
1. Import `MazPicker`
2. Configure `MazPicker` as you want

**Expected behavior**
The component is working as expected.

**Screenshots**
![Annotation 2020-06-24 094719](https://user-images.githubusercontent.com/31876571/85492647-b4090780-b5ff-11ea-8c5e-95bfdb54b911.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83

**Additional context**
The warnings appear when you open (click on) the picker and when changing month/year (haven't tested with time).

**Comment by LouisMazel** [comment]
Thanks again ! 

Solved in 1.2.4: https://github.com/LouisMazel/maz-ui/releases/tag/v.1.2.4
