### ISSUE TITLE
[Issue][<MazPhoneNumberInput>Lag in certain conditions

### ISSUE THREAD

**Issue by Temepest74** [LouisMazel/maz-ui#591]
I try to make a global phone number component based on your phone component as I don't want to repeat my config each time
This work when I use the component directly inside my form file
```
                <MazPhoneNumberInput v-model="form.phone" />
```
but if I change my set-up, and add this to my form file
```
                <PhoneNumberInput v-model="form.phone" />
```
and the content of PhoneNumberInput is
```
  import MazPhoneNumberInput from 'maz-ui/components/MazPhoneNumberInput'

<script setup lang="ts">

const props = defineProps<{
    modelValue: string;
}>();
const emits = defineEmits(["update:modelValue"]);
</script>

<template>
    <MazPhoneNumberInput :value="modelValue" @input="$emit('update:modelValue', ($event.target as HTMLInputElement).value)">
    </MazPhoneNumberInput>
</template>
```
The input becomes just so slot / bugged that I am unable to use it. It skips some keystrokes entirely and some functions such as select all then back arrow does not work anymore

**Comment by Temepest74** [comment]
Update: this is the cause :value="modelValue"

**Comment by LouisMazel** [comment]
With Vue 3, you must use `model-value` instead of `value` and `@update:model-value` event instead of `@input`.

```vue
<template>
    <MazPhoneNumberInput :model-value="modelValue" @update:model-value="$emit('update:modelValue', $event)">
    </MazPhoneNumberInput>
</template>
```
