### ISSUE TITLE
[Issue][Configuration Nuxt3] Cannot find module '...' or its corresponding type declarations.

### ISSUE THREAD

**Issue by TwentyCCent** [LouisMazel/maz-ui#620]
**Describe the bug**
Les modules de maz-ui ne sont pas reconnus en utilisant la syntaxe ESM

**To Reproduce**
"nuxt": "^3.7.3",
...
"maz-ui": "^3.11.4"

Dans mon package.json j'ai bien déclaré le type module
"type": "module",

Voici ma config de Nuxt comme conseillé il me semble :
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  srcDir: 'src/',
  css: ['maz-ui/css/main.css', '@/assets/main.css'],
  build: {
    transpile: ['maz-ui'],
  },

J'ai ajouté la déclaration du module, mais cela n'a rien changé :
declare module 'maz-ui' {
  export * from 'maz-ui/modules'
}

**Screenshots**
<img width="754" alt="Capture d’écran 2023-09-19 à 08 30 42" src="https://github.com/LouisMazel/maz-ui/assets/75541353/47225ad3-ecb6-449c-857d-5f7510b27651">

**Desktop (please complete the following information):**

- OS: Mac OS Ventura

Merci du retour

**Comment by LouisMazel** [comment]
Solved in **v3.12.0**

Please let know if it's good for you

**Comment by TwentyCCent** [comment]
Thanks, it works well for the components, both solutions were ok, I upgraded. The library looks excellent, bravo for your work! If I find a moment I'd be interested in contributing.

**Comment by LouisMazel** [comment]
@TwentyCCent Nice! Thanks you, it's a pleasure to hear!

Yeees! of course, it’s with pleasure that you can contribute! If you some ideas of components, plugins, etc or something else to improve, it's really welcome.
