### ISSUE TITLE
MazPhoneNumberInput has a  bug

### ISSUE THREAD

**Issue by Sunny264** [LouisMazel/maz-ui#654]
1: There is a problem with the arrow, clicking on it does not respond, and the drop-down option will not disappear
2: Losing focus on the mobile end, the dropdown option will not disappear
![image](https://github.com/LouisMazel/maz-ui/assets/36886899/3d8d312a-69b9-4fb2-95f4-68b6ce24a912)

**Comment by LouisMazel** [comment]
Fixed in v3.17.1
