### ISSUE TITLE
[FEATURE](MazPhoneNumberInput) Add option to control formatting of v-model and input value shown

### ISSUE THREAD

**Issue by idesignzone** [LouisMazel/maz-ui#655]
When using "MazPhoneNumberInput", as described in the docs: "Phone number is formatted while typing".
Number is formatted as a national format. Some of these national standards have changed over time but not updated in global database it seems and its confusing for some country users. They try to correct the formatted number again!
Having an option to format the number internationally and not nationally will help this issue.

**Comment by LouisMazel** [comment]
Hi,

I understand, I can add an option to do this.
I will come back here when it's done

**Comment by idesignzone** [comment]
In this [example](https://github.com/LouisMazel/vue-phone-number-input)  national number seems to be correct. However can't get it to work with vue3.

**Comment by LouisMazel** [comment]
> In this [example](https://louismazel.github.io/vue-phone-number-input) national number seems to be correct. However can't get it to work with vue3.

Yes, it's a Vue 2 plugin.

**Comment by LouisMazel** [comment]
@idesignzone 

Could you give me more information about your needs? I'm not sure if I understand your request. 

Can you tell me what you expect? 
Which data (v-model, results[...], etc) should be changed? Wich format?

Give me an example and tell me what's happening currently and what you want to change?

Because in the `@update` event, you have all the data and formats.

**Comment by idesignzone** [comment]
@LouisMazel problem is with the way number is shown in the input.
for example I show country of Kazakhstan:
![image](https://github.com/LouisMazel/maz-ui/assets/3501211/1828380f-eb00-475a-a583-b7cc20798c79)
There is an 8 in the beginning that is added by auto formatter and is wrong. There is no such a digit and users from this country consider it a wrong number and try to retype it again. 
in the other hand you have another [example](https://louismazel.github.io/vue-phone-number-input) that don't have this problem.
![image](https://github.com/LouisMazel/maz-ui/assets/3501211/b268085d-f190-4f73-be53-ada5f017f4ac)

so thanks to result we can get any format we need for submission, but the format as you type feature is converting some countries number to a wrong number and sometimes even removes the last digit.
This is not only for Kazakhstan. There are other countries with same formatting problem. 

So the idea is to either:
disable the auto formatting.
show the correct National number inside the field.
or just show the international number inside the field instead of national number like:

![image](https://github.com/LouisMazel/maz-ui/assets/3501211/630e59e9-8290-41d0-85c1-b91226d8852c)

Hope I could explain it more clearly. Please let me know if you have more question.

**Comment by LouisMazel** [comment]
Ok perfect, thank you, I got it !

In the example you gave, it's an old library that uses an old version of libphonenumber-js.
I couldn't have this formatting but I will give an option to deactivate the auto-format "as you type" as you propose.

I'll let you know when all this is done (I have other developments to report as well) :)

**Comment by LouisMazel** [comment]
@idesignzone 

I released v3.19.0: 
- https://github.com/LouisMazel/maz-ui/releases/tag/v3.19.0

MazPhoneNumberInput has now `no-formatting-as-you-type` to disable the auto-format ;)
