### ISSUE TITLE
Error when using MazPhoneNumberInput (libphonenumber-js can not be found)

### ISSUE THREAD

**Issue by bsiegrist** [LouisMazel/maz-ui#690]
I have a VueJS 3.3.4 App with Vite/Pinia/Vuetify/Axios/Router and I followed your Get-Startet Guide. 
Global component installation got me following Error: 

> Uncaught Error: Could not resolve "libphonenumber-js" imported by "maz-ui". Is it installed?
>     at optional-peer-dep:__vite-optional-peer-dep:libphonenumber-js:maz-ui:1:7
> (anonymous) @ optional-peer-dep:__vite-optional-peer-dep:libphonenumber-js:maz-ui:1

– tried importing in Component instead of globally (same error)
– libponenumber-js is included in Packages, but I also tryed to install separately (same error)
– tried to comment out all other import, so they don't affect mazPhoneNumberInput (same error)
– tried to import all components of maz-ui (same error)

Any Ideas what else could be done?

**Comment by bsiegrist** [comment]
I installed libphonenumber-js but it didn't work unfortunately.

**Comment by LouisMazel** [comment]
Did you check the codesandbox link I shared?

Can a part of your code where you use the component? 
The best way it's a reproduction link with codesandbox
