### ISSUE TITLE
MazPhoneNumberInput format in phone-input

### ISSUE THREAD

**Issue by Sergdan1992** [LouisMazel/maz-ui#707]
formatNational number  is misleading users about zero in start of number. Users often use input in some country and zero in start of phone-number is difficult to understand.
What about provide some props for chosen format or variant for display in input?
Maybe you can use 'formatInternational' without country code? Or use whole number from 'formatInternational'?

**Screenshots**
![lohITRN](https://github.com/LouisMazel/maz-ui/assets/55101680/80edb253-2759-426e-bf30-01251cfbfd8f)

**Comment by LouisMazel** [comment]
Hi @Sergdan1992, 

The zero is automatically added by the "As you type" feature.
This feature normalizes the number entered, with the “best” format.

If you don't want this behavior, you can simply disable it like this:

```html
<MazPhoneNumberInput no-formatting-as-you-type />
```

Sounds good for you?

**Comment by Sergdan1992** [comment]
Hi [LouisMazel](https://github.com/LouisMazel),

If  i use `no-formatting-as-you-type`, then in editing form in input full number like this [example](https://i.imgur.com/SYyFX1n.png)

**Comment by LouisMazel** [comment]
Maybe the solution to not mislead users would be to display the name of the country in the country selector instead of the calling code. To have this UI:

<img width="710" alt="image" src="https://github.com/LouisMazel/maz-ui/assets/12446546/f9f178d2-e649-4cc0-a729-7a57266ca577">

What do you think about it?

I will add a prop `country-selector-shows-name` to display country name (and `country-selector-width` to increase or reduce the size of the country selector)

**Comment by LouisMazel** [comment]
New options available in [v3.22.1](https://github.com/LouisMazel/maz-ui/releases/tag/v3.22.1)

**Comment by Sergdan1992** [comment]
Sounds good to me! Thank you!
I found a partial solution. I use `parsePhoneNumber` from 'libphonenumber-js', for parsing country from existing phone and use `country-code` prop.

`
<script setup>
import parsePhoneNumber from 'libphonenumber-js'

const parsedPhone = parsePhoneNumber(props.phone)
countryCode.value = parsedPhone?.country
phoneValue.value = parsedPhone?.nationalNumber || ''
</script>
<template>
<maz-phone-number-input 
  v-model="phoneValue"
  :country-code="countryCode"
  @update="onUpdate"
/>
</template>
`

Maybe it's help someone!
I appreciate your work!
