### ISSUE TITLE
Prop no-validation does not work with MazPhoneNumberInput component

### ISSUE THREAD

**Issue by Fishlex0** [LouisMazel/maz-ui#718]
**Describe the bug**
The flag _"no-validation"_ does not work on MazPhoneNumberInput. The flag is described in the component [features list](https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input).

**To Reproduce**
1. Add "no-validation" flag on the MazPhoneNumberInput.
2. Type a phone number.

**Expected behavior**
It should not make the border red if the number is invalid, or green if it's correct.

**Screenshots**
![image](https://github.com/LouisMazel/maz-ui/assets/48848991/e3b6b2f8-93d0-4225-92f5-a8255186b375)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version118.0.5993.120

**Comment by LouisMazel** [comment]
Hi @Fishlex0,

I will release a new version to handle this states (error and success). 

New props : 
- `no-validation-success`: to disable success UI state
- `no-validation-error`: to disable success UI state

PR: #719

**Comment by LouisMazel** [comment]
Released in v3.21.4

Changelog: https://github.com/LouisMazel/maz-ui/releases/tag/v3.21.4
