### ISSUE TITLE
[Country select does not change if country-code prop is set] [MazPhoneNumberInput]

### ISSUE THREAD

**Issue by Fishlex0** [LouisMazel/maz-ui#721]
**Describe the bug**
If I set country-code prop on MazPhoneNumberInput and then I change the country, the value remains as the one I added as a prop. If this is the intended behaviour, how can I set a default value for the country select other than "US" and still be able to change the country code?

**UPDATE**
The country code does change internally but it is not reflected in the view of the component, see the picture below where I selected Egypt but United Kingdom is still displayed because it was set initially as the country-code.

**To Reproduce**

1. Add the country-code prop with a country value, for instance 'GB'
2. Try to select another value from the country select
3. The country code is not changing.

**Expected behavior**
The country code should change when I select another country.

**Screenshots**
![image](https://github.com/LouisMazel/maz-ui/assets/48848991/599cc3da-7739-43a6-8b5d-e8f21bdbf3a0)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version118.0.5993.120

**Comment by LouisMazel** [comment]
Hi @Fishlex0,

Like you can see in [this example](https://stackblitz.com/edit/vue3-vite-typescript-starter-1w2hyd?file=package.json,src/App.vue), you use the two-way binding model to make the country code overridable. 

```vue
<template>
  <MazPhoneNumberInput v-model="phoneNumber" v-model:country-code="countryCode" />
</template>

<script lang="ts" setup>
  import MazPhoneNumberInput, { type CountryCode } from 'maz-ui/components/MazPhoneNumberInput'
  
  const phoneNumber = ref<string>()
  const countryCode = ref<CountryCode>('GB')
</script>
```
