### ISSUE TITLE
[BUG][MazPhoneNumberInput] flags z-index issue while select list of countries is open

### ISSUE THREAD

**Issue by LouisMazel** [LouisMazel/maz-ui#73]
Using your control with vue formulate forms, and in form i need several rows with phone-number-input. And this problem occured after opening dropdown. See screenshot
![image](https://user-images.githubusercontent.com/36773117/87035335-da2eca00-c1f1-11ea-8db7-1b8e0b24350a.png)

After research of this problem possible solution may be like this : default display value for **maz-select__options-list** is display: none; and there is maz-flex class on this block that should set display: flex; and as chrome devtools shows it should work but there is small moment that display: flex; should be set dynamically

**Comment by EugeneVaida** [comment]
If it is possible, could you please let me know when the issue can be resolved? Because if it requires a lot of time I will need to implement a temporary solution.
So, if you could provide me with the status of the issue, it will be really great!
Thank you in advance and have a nice day!

**Comment by LouisMazel** [comment]
@EugeneVaida 

Solved in release [**1.2.16**](https://github.com/LouisMazel/maz-ui/releases/tag/v1.2.16) :fire:
