### ISSUE TITLE
[Issue][MazSelect] Support cyrilic alphabet

### ISSUE THREAD

**Issue by Sergdan1992** [LouisMazel/maz-ui#738]
**Describe the bug**
MazSelect search does not work with other than English. `mainInputKeyboardHandler` has [checker](https://github.com/LouisMazel/maz-ui/blob/master/packages/lib/components/MazSelect.vue#L419) for only latin alphabet.

**To Reproduce**
[Stackblitz](https://stackblitz.com/edit/vitejs-vite-qafphw?file=src%2Fcomponents%2FAppSelect.vue&terminal=dev) with cyrillic options. Try search with query 'білий' or 'чорний'. 

**Expected behavior**
Add cyrilic alphabet or  change checker entirely, for support other languages.

**Comment by LouisMazel** [comment]
Solved in [v3.23.0](https://github.com/LouisMazel/maz-ui/releases/tag/v3.23.0) 

Let me know if it's good for you
