### ISSUE TITLE
MazSelect @change event not working 

### ISSUE THREAD

**Issue by Ok9xNirab** [LouisMazel/maz-ui#74]
My Code is here : 

```vue
<MazSelect
   v-model="wacfilter.type"
   @change="filterChange()"
   placeholder="Choose a type"
   left-icon-name="flash_on"
   :options="filterTypes"
/>
```

Method :

```js
filterChange() {
      console.log("hello world");
 }
```

I dont know why its not working !!

**Comment by LouisMazel** [comment]
I will add the support of this event, but you can use ‘@input’ event instead 

Thanks

**Comment by Ok9xNirab** [comment]
Thanks @LouisMazel , for Helping !!

I appreciate your work & Go Ahead !!

**Comment by LouisMazel** [comment]
Which version do you use? Do you use Vue 2 or Vue 3?

@fillobotto 

With Vue 3, you should use the event `@update:model-value`, but `@change` should works too
