### ISSUE TITLE
Autofocus to inputs

### ISSUE THREAD

**Issue by alexsonnay** [LouisMazel/maz-ui#75]
Great plugin ! 

Would it be possible to add autofocus option to all type of inputs such as MazInput ?

**Comment by LouisMazel** [comment]
Hi @alexsonnay,

What do you mean by "autofocus"?
When and how do you want to trigger the autofocus? Have you an example ? 

Do you want me to put an "autofocus" function in the component API?
Then you will doing this: 

```js
const autofocus = () => {
  this.$refs['REF_NAME_OF_INPUT'].focus()
}
```
