### ISSUE TITLE
Flag position when noCountrySelector enabled

### ISSUE THREAD

**Issue by alexsonnay** [LouisMazel/maz-ui#76]
<img width="141" alt="Screenshot 2020-07-14 at 20 46 38" src="https://user-images.githubusercontent.com/28756458/87464277-24a9af80-c613-11ea-8b20-d245ff9d569b.png">

**Comment by LouisMazel** [comment]
I will release this option soon: 
Follow this PR: **[release-v1.2.15]** #80

**Comment by LouisMazel** [comment]
Fixed & released: https://github.com/LouisMazel/maz-ui/releases/tag/v1.2.15
