### ISSUE TITLE
Ability to set set maz-phone-number-input placeholder 

### ISSUE THREAD

**Issue by jmohler1970** [LouisMazel/maz-ui#77]
**Is your feature request related to a problem? Please describe.**

maz-phone-number-input placeholder should be able to be set to something. Or blank if necessary

**Describe the solution you'd like**
It should follow the same approach as maz-input

**Describe alternatives you've considered**
N/A

**Additional context**

This one field looks strange

![Screen Shot 2020-07-15 at 12 35 53 PM](https://user-images.githubusercontent.com/2627663/87587997-cd99ee00-c697-11ea-85c8-c8cf1de24d61.png)

**Comment by LouisMazel** [comment]
I will release this option soon: 
Follow this PR: **[release-v1.2.15]** #80 

Otherwise, you cna use the "translations" API option: 

```
:translations="{
  countrySelectorLabel: 'Code pays',
  countrySelectorError: 'Choisir un pays',
  phoneNumberLabel: 'Numéro de téléphone',
  example: 'Exemple :'
}"
```

`phoneNumberLabel` is the placeholder

Thanks for your feedback !

**Comment by LouisMazel** [comment]
Fixed & released: https://github.com/LouisMazel/maz-ui/releases/tag/v1.2.15
