### ISSUE TITLE
[Issue][MazDropzone]

### ISSUE THREAD

**Issue by YusufTezel** [LouisMazel/maz-ui#790]
**Describe the bug**
I am using the code provided here https://louismazel.github.io/maz-ui-3/components/maz-dropzone and **it works when i create a build and run it, but when I run it in dev mode it does not work**, notice my launch setup, where I use "dev" as argument. 

**To Reproduce**

1. Create a new page in nuxt 3, call it dropzone.vue and put it under pages directory
2. Go to https://louismazel.github.io/maz-ui-3/components/maz-dropzone and copy the provided code and paste it in dropzone.vue
3. Start the application, I am using vs code and my launch.json contain this (I am running fullstack: nuxt)
{
  "version": "0.2.0",
  "configurations": [
      {
          "type": "chrome",
          "request": "launch",
          "name": "client: chrome",
          "url": "http://localhost:3000",
          "webRoot": "${workspaceFolder}"
      },
      {
          "type": "node",
          "request": "launch",
          "name": "server: nuxt",
          "outputCapture": "std",
          "program": "${workspaceFolder}/node_modules/nuxi/bin/nuxi.mjs",
          "args": [
              "dev"
          ]
      },
  ],
  "compounds": [
      {
          "name": "fullstack: nuxt",
          "configurations": [
              "server: nuxt",
              "client: chrome"
          ]
      }
  ]
}
,`
4. Navigate to the dropzone (/dropzone) page in browser
5. See error

**Expected behavior**
I expected it to work like in the example here https://louismazel.github.io/maz-ui-3/components/maz-dropzone.

**Screenshots**
The error message
![image](https://github.com/LouisMazel/maz-ui/assets/1453654/03c24832-e26d-4436-99a7-cd22dc03dfc0)
Spinner that keeps spinning 
![image](https://github.com/LouisMazel/maz-ui/assets/1453654/62ce1041-1b50-429a-8a93-0b1981b1cb90)

**Additional context**
package.json
`{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "^1.0.0-beta.0",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@types/node": "^18.18.4",
    "autoprefixer": "^10.4.16",
    "firebase-admin": "^11.11.0",
    "firebase-functions": "^4.4.1",
    "firebase-functions-test": "^3.1.0",
    "nuxt": "^3.7.4",
    "nuxt-icon": "^0.5.0",
    "postcss": "^8.4.31",
    "postcss-scss": "^4.0.9",
    "sass": "^1.69.2",
    "tailwindcss": "^3.3.3"
  },
  "dependencies": {
    "@popperjs/core": "^2.11.8",
    "@vee-validate/nuxt": "^4.11.8",
    "dayjs": "^1.11.10",
    "dropzone": "^5.9.3",
    "firebase": "^10.4.0",
    "libphonenumber-js": "^1.10.49",
    "maz-ui": "^3.29.3",
    "postinstall": "^0.8.0",
    "vanilla-cookieconsent": "3.0.0-rc.17",
    "vue-toast-notification": "^3.1.1",
    "yup": "^1.3.2"
  },
  "overrides": {
    "vite-plugin-inspect": "0.7.38"
  }
}
`

and my nuxt.config.ts file:

`// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    '@nuxtjs/tailwindcss',
    '@vee-validate/nuxt',
    'nuxt-icon',
    'maz-ui/nuxt'
  ],
  css: ['vue-toast-notification/dist/theme-default.css', '@/assets/css/maz-ui-variables.css'],
  app: {
    head: {
      link: [
        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@300;700&display=swap' },
      ],
    },
  }
})`

**Comment by LouisMazel** [comment]
Have you installed `dropzone` with this command?

```bash
npm install dropzone@^5.9.3
```

**Comment by LouisMazel** [comment]
I can reproduce the bug and investigate it soon, but I don't have time before Monday.

Follow this PR: https://github.com/LouisMazel/maz-ui/pull/791

Thanks for your feedback

**Comment by YusufTezel** [comment]
> I can reproduce the bug and investigate it soon, but I don't have time before Monday.
> 
> 
> 
> Follow this PR: https://github.com/LouisMazel/maz-ui/pull/791
> 
> 
> 
> Thanks for your feedback

Nice, thank you.

**Comment by LouisMazel** [comment]
> Thanks, I knew you wouldn't rest until you did it, the spirit of a true developer. 😀

Exactly, it's stronger than me 😅
