### ISSUE TITLE
[FEATURE] Add Types Definition

### ISSUE THREAD

**Issue by RacerDelux** [LouisMazel/maz-ui#82]
When running typescript in Vue, you get errors when trying to compile this project. With Vue 3 moving to a typescript core, I think this becomes even more useful.

**Comment by LouisMazel** [comment]
Hi @RacerDelux 

I agree with you, I must do it.
Can you help me ?  I have never done that.

Do you have an example or something for a component?

I am alone for this project and I don't have much time at the moment

**Comment by LouisMazel** [comment]
I released the support of typescript in **v1.3.1**

Release: [https://github.com/LouisMazel/maz-ui/releases/tag/v1.3.1](https://github.com/LouisMazel/maz-ui/releases/tag/v1.3.1)

**Comment by RacerDelux** [comment]
@LouisMazel Oof - I was torn away from checking his for a while. I am glad you got it working though!
