### ISSUE TITLE
[BUG][MazPhoneNumberInput] Phone number input is not completely clear

### ISSUE THREAD

**Issue by BilalShah3** [LouisMazel/maz-ui#827]
**Describe the bug**
last char in input was not clear.

**To Reproduce**

1. Go to 'MazPhoneNumberInput'
2. Enter 'Any phone number'
3. Clear 'Input field and remove focus from the field '
4. See 'last char'

**Expected behavior**
A input field should be clear .

**Screenshots**
![Screenshot 2023-12-19 225643](https://github.com/LouisMazel/maz-ui/assets/110353066/9e5f0dfa-a0bb-48fd-bad8-4751d8a41e53)

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome, Fire Fox]
- Version [3.29.11]

**Comment by LouisMazel** [comment]
Hi @BilalShah3, 

Can you share your code or a reproduction link? 

Thanks

**Comment by BilalShah3** [comment]
here is my vue component code

<template>
 
    <MazPhoneNumberInput
        :model-value="props.context._value"
        @update:model-value="handleInput($event)"
        show-code-on-list
        @update="handleUpdate($event)"
        :preferred-countries="['FR', 'BE', 'DE', 'US', 'GB']"       
        :success="results?.isValid"
        :id="props.context.id"
        size="sm"
    />

</template>

<script setup>

import MazPhoneNumberInput from 'maz-ui/components/MazPhoneNumberInput'

const props = defineProps({
    context: Object
}) 

const results = ref()

function handleInput($event) {
    $event? props.context.node.input($event):props.context.node.input('')
}

function handleUpdate($event) {
    results.value = $event
}


</script>

**Comment by BilalShah3** [comment]
![291678139-9e5f0dfa-a0bb-48fd-bad8-4751d8a41e53](https://github.com/LouisMazel/maz-ui/assets/110353066/9c152fce-e0e2-4a64-8a67-8ffa1d8a6611)

https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input

**Comment by LouisMazel** [comment]
Hi @BilalShah3 

Thanks for your feedback, the issue is solved in v3.29.12. 

[**Release Note**](https://github.com/LouisMazel/maz-ui/releases/tag/v3.29.12)

**Comment by BilalShah3** [comment]
thanks your welcome
