### ISSUE TITLE
[Issue][<MazPhoneNumberInput>] flag position when no countrySelector.placeholder is provided

### ISSUE THREAD

**Issue by marian010** [LouisMazel/maz-ui#828]
**Describe the bug**
The flag icon's position is incorrect when no countrySelector.placeholder is provided.

**To Reproduce**

1. Remove the countrySelector.placeholder attribute.

**Expected behavior**
The flag icon should be correctly positioned.

**Screenshots**
<img width="134" alt="image" src="https://github.com/LouisMazel/maz-ui/assets/69600603/952fef56-8a96-443a-b0a7-9ec895f3ec1d">

**Desktop (please complete the following information):**

- OS: [macos]
- Browser [chrome]
- Version [3.28.6]

**Comment by LouisMazel** [comment]
Hi @marian010,

Thanks for your feedback, the issue is solved in v3.29.12. 

[**Release Note**](https://github.com/LouisMazel/maz-ui/releases/tag/v3.29.12)
