### ISSUE TITLE
[Country select does not change if country-code prop is set] [MazPhoneNumberInput]

### ISSUE THREAD

**Issue by jannkasper** [LouisMazel/maz-ui#854]
**Describe the bug**

This code should make France as a default countryCode, but countryCode is based on my browser language. Cannot change it anyway.
```
  <MazPhoneNumberInput
    country-code="FR"
  />
```
You can see this even in your documentation. CountryCode is based on my browser language even when your code sample set 'FR'

**Screenshots**
<img width="829" alt="Screenshot 2024-01-03 at 11 12 23" src="https://github.com/LouisMazel/maz-ui/assets/46023973/654f3336-83c6-4f4d-9ed4-80a6f531fa76">

**Comment by LouisMazel** [comment]
Hi @jannkasper,

Thanks for your feedback. 
I just released a new version [v3.31.4](https://github.com/LouisMazel/maz-ui/releases/tag/v3.31.4) to fix this issue. 

N.B: 
- The component uses the browser locale if no country code is provided. You can disable it by adding the prop `no-use- browser-locale`
- The country code prop is a model, you may use it like this: `<MazPhoneNumberInput v-model:country-code="countryCode" />`
- You can also add the prop `fetch-country` to get the user's locale with his IP (with https://ipwho.is) and not the browser locale.
