### ISSUE TITLE
country-locale not changed with Change lang in <MazPhoneNumberInput>

### ISSUE THREAD

**Issue by RadwaMosaad** [LouisMazel/maz-ui#865]
I am using maz-ui version "3.30.0"  with Nuxt version 3.8.2
my website has 2 languages (English/Arabic) So I need country list changes with the website language change 
here is my code in the template
`<MazPhoneNumberInput
              v-model="phoneNumber"
              @update="phoneNumberResults = $event"
              fetch-Country="true"
              no-example
              :size="'sm'"
              :key="$i18n.locale"
              :country-locale="$i18n.locale === 'en' ? 'en-US' : 'ar-EG'"
              :translations="{
                countrySelector: {
                  placeholder: '',
                  error: 'Choose country',
                  searchPlaceholder: 'Search a country',
                },
                phoneInput: {
                  placeholder: $t('PhoneNumber') + '*',
                  example: 'Example:',
                },
              }"
              :error="
                vMain$.phoneNumber.$dirty &&
                showRequiredVaidationErrors('phoneNumber')
              "
              :success="!showRequiredVaidationErrors('phoneNumber')"
              @keypress="vMain$.phoneNumber.$touch"
              @blur="vMain$.phoneNumber.$touch"
            />`
 and in script 
 `import MazPhoneNumberInput from "maz-ui/components/MazPhoneNumberInput";`
 But when I change the language it keeps the country list with the language I start the website with 
I test it on Google Chrome version 120.0.6099.130
 Can you advise me

**Comment by LouisMazel** [comment]
Hi @RadwaMosaad, 

Thanks for your feedback. I just released a new version [v3.31.5](https://github.com/LouisMazel/maz-ui/releases/tag/v3.31.5) to make this prop option reactive and fix this issue. 

Enjoy :)

**Comment by RadwaMosaad** [comment]
It works Now, Thanks for your fast response @LouisMazel
