### ISSUE TITLE
[BUG][mazPicker]  minDate and maxDate for date/time options  

### ISSUE THREAD

**Issue by aliciahogue** [LouisMazel/maz-ui#87]
**Describe the bug**

I have mazPicker with a min date set as "2020-08-01T15:00:00.000Z"   Current value is set as "2020-08-02T15:00:59.999Z" but in the time picker portion, all of the times below 15:00:00 are blanked out even though the date is set to the 02 and not the 01.

![Screenshot from 2020-08-02 18-07-22](https://user-images.githubusercontent.com/4161629/89132766-eb1ae480-d4ec-11ea-974c-4d0cb5e1baf7.png)

**Comment by LouisMazel** [comment]
Solved in the **[release v1.4.1](https://github.com/LouisMazel/maz-ui/releases/tag/v1.4.1)**

Let me know if you have any others bugs

Thanks for you feedback 🙌
