### ISSUE TITLE
[Issue][MazPhoneNumberInput] Can't reset the component

### ISSUE THREAD

**Issue by jlswanson28694** [LouisMazel/maz-ui#872]
Great component, but I can't seem to reset the input after the user enters their number. I have the MazPhoneNumberInput v-modeled to a ref `phoneNumber`, which works as expected until I want to clear it. I've tried setting `phoneNumber` to an empty string, `null`, and `undefined`, but the component continues to display the text from whatever value was entered before I clear it out.

**Comment by LouisMazel** [comment]
Hi @RadwaMosaad, 

Thanks for your feedback. I just released a new version [v3.31.6](https://github.com/LouisMazel/maz-ui/releases/tag/v3.31.6) to fix the reactivity of this model. 

Enjoy :)
