### ISSUE TITLE
maz-picker 

### ISSUE THREAD

**Issue by BerndtDavid** [LouisMazel/maz-ui#88]
Nice component!

Documentation:

1. Persistent description says: shows dark mode
2. NoShortcuts description says: disable time picker

Enhancement:

Any chance of adding a prop to prevent scrolling left months before min-date, and right after max-date?

**Comment by LouisMazel** [comment]
It's solved ! 

For the prop to prevent scrolling, it's not planned for the moment...

Thanks for your feedback !
