### ISSUE TITLE
[BUG][global] keyboard accessibility

### ISSUE THREAD

**Issue by danielroe** [LouisMazel/maz-ui#89]
**Describe the bug**
I really like this UI library - clean, fresh & creative.

But many of the input components are not keyboard accessible.

- [x] checkbox does not have a focus style
- [x]  dropzone is not focusable
- [x]  radio button does not have a focus style
- [x]  slider is not focusable
- [x]  switch is not focusable

There are some other ways components could *improve* their accessibility as well, such as the tabs component, which should respond to certain key presses, and use aria-roles - but I'm mainly raising this initial issue to focus on very basic keyboard accessibility for the input components above.

**To Reproduce**
This is reproducible on https://louismazel.github.io/maz-ui/

**Comment by LouisMazel** [comment]
All are solved :fire:

**Release: [v1.4.0](https://github.com/LouisMazel/maz-ui/releases/tag/v1.4.0)**

**Comment by danielroe** [comment]
Very nice solutions 😃
