### ISSUE TITLE
[BUG][MazPhoneNumberInput] Strange behavior when delete (backspace) symbols from russian format phone number

### ISSUE THREAD

**Issue by andron58** [LouisMazel/maz-ui#90]
It's reproduced on demo page https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input
select Russia country code, then put for example this phone number 9992223345, and then press a backspace button. After that symbols not deleted, until the '8' ыньищд will not take up the whole field.

**Comment by Pmnchk275** [comment]
Hi, any progress on this bug?

**Comment by LouisMazel** [comment]
After long work, it's solved in the 1.4.0 version

One change: To update the phone number, please use the new prop `default-phone-number` instead of `value` (v-model)

**Release: [v1.4.0](https://github.com/LouisMazel/maz-ui/releases/tag/v1.4.0)**
