### ISSUE TITLE
[Issue][MazPhoneNumberInput] Formatting doesn't work without v-model binding

### ISSUE THREAD

**Issue by b01010110** [LouisMazel/maz-ui#914]
**Describe the bug**
I don't know how much it's important behavior, but I decided to report about it.
When I started working with this component, I spent lots of time to understand it, I thought that it's a bug!

Formatting doesn't work without v-model binding.

**To Reproduce**

1. Go to https://maz-ui.com/components/maz-phone-number-input
2. Click on the second phone-number-input and type the example number.

**Comment by LouisMazel** [comment]
Hi @b01010110,

I completely rewrote the component to improve it and fix some bugs.
I released [v3.37.0](https://github.com/LouisMazel/maz-ui/releases/tag/v3.37.0) and this version fixes your bug.

Let me know if anything doesn't work as expected.

Enjoy
