### ISSUE TITLE
[Issue][MazBottomSheet, MazDialog] Huge "X" icon on iOS

### ISSUE THREAD

**Issue by sourcecodeit** [LouisMazel/maz-ui#919]
**Describe the bug**
MazBottomSheet and MazDialog show a huge "X" icon on iOS (tested on simulator). If you change any CSS property from the inspector it fixes it immediatley.

**To Reproduce**
I don't have a public URL

**Expected behavior**
"X" icon with correct icon.

**Screenshots**
<img width="410" alt="image" src="https://github.com/LouisMazel/maz-ui/assets/22499359/a7c9097b-80fc-4363-a8ec-25e8098f8aac">
<img width="376" alt="image" src="https://github.com/LouisMazel/maz-ui/assets/22499359/a78f3cc2-46cf-4167-82bb-487e27bbd2dc">

**Smartphone (please complete the following information):**

- Device: iPhone 14 (iOS simulator )
- OS: iOS 14

**Comment by sourcecodeit** [comment]
It looks like a CSS conflict but it looks all fine and it doesn't happen on Chrome.

<img width="1355" alt="image" src="https://github.com/LouisMazel/maz-ui/assets/22499359/508f0ade-f826-4045-bbd9-c47c54469bad">
<img width="1088" alt="image" src="https://github.com/LouisMazel/maz-ui/assets/22499359/e3aa64f6-690b-4eeb-b4c3-2bca2dfba5a4">
<img width="1352" alt="image" src="https://github.com/LouisMazel/maz-ui/assets/22499359/07d5afbe-697c-4fd1-8116-d49dd58df618">

**Comment by sourcecodeit** [comment]
I added this code to fix it:

```
.m-backdrop-content {
	.m-bottom-sheet__close, 
	.m-dialog-closebtn {
		width: 44px;
	}
}
```

**Comment by LouisMazel** [comment]
Hi @sourcecodeit,

In your inspector and in your CSS rules I can see : 

```css
span svg {
  height: 100%;
  width: 100%;
}
```

Where does this rule come from? I think this rule is the problem.
It's not the CSS of maz-ui.

You can try the component from the documentation in the simulator to test it: https://maz-ui.com/components/maz-dialog

**Comment by sourcecodeit** [comment]
You

> Hi @sourcecodeit,
> 
> In your inspector and in your CSS rules I can see :

You're right! That's a not-scoped rule I put in a component, thanks!
