### ISSUE TITLE
[Issue][MazPicker] Chevron icon not open/close picker

### ISSUE THREAD

**Issue by magdawernik** [LouisMazel/maz-ui#920]
**Describe the bug**
In a Maz DatePicker the arrow on the right side of the input is not enabling the dropdown opening and closing. 

**To Reproduce**

1. Go to 'https://maz-ui.com/components/maz-picker'
2. Click on the arrows in the example of 'Date Time Picker'
4. See error: the dropdown doesn´t open/close when clicked on the arrow. 

**Expected behavior**
 The dropdown should open/close when clicked on the arrow

**Screenshots**
<img width="498" alt="image" src="https://github.com/LouisMazel/maz-ui/assets/134924316/e6db8c4c-94ab-4413-9bc0-e2e69a47e60b">

**Desktop (please complete the following information):**

- Browser [chrome, edge]

**Additional context**
The feature doesn´t work neither in my website nor in the Maz Input documentation.

**Comment by LouisMazel** [comment]
Hi @magdawernik,

Will be fixed in 3.32.0.

**Comment by LouisMazel** [comment]
[v3.32.0](https://github.com/LouisMazel/maz-ui/releases/tag/v3.32.0) is released
