### ISSUE TITLE
[BUG][MazSelect] Can't tab out of the select box

### ISSUE THREAD

**Issue by danielroe** [LouisMazel/maz-ui#96]
**Describe the bug**
When tabbing into the MazSelect component, it's impossible to tab on or exit the component via keyboard.	

**To Reproduce**
1. Go to https://louismazel.github.io/maz-ui/documentation/maz-select
2. Tab into the select component and try to tab out

**Expected behavior**
I expect to be able to tab in, select an option, press enter to select it and then tab out.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Firefox, Safari
 - Version: latest on website

**Comment by LouisMazel** [comment]
Solved in the **[release v1.4.1](https://github.com/LouisMazel/maz-ui/releases/tag/v1.4.1)**

Thanks again for you feedback 🙌
